Gyman\Bundle\MembersBundle\Entity\Member:
  type:   entity
  table:  members
  repositoryClass:  Gyman\Bundle\MembersBundle\Entity\MemberRepository
  embedded:
    email:
      class: Gyman\Bundle\MembersBundle\Entity\EmailAddress
      columnPrefix: false
    details:
      class: Gyman\Bundle\MembersBundle\Entity\Details
      columnPrefix: false

  id:
    id:
      type: integer
      generator: { strategy: AUTO }

  gedmo:
    soft_deleteable:
      field_name: deletedAt
      time_aware: false

  manyToMany:
#    vouchers:
#      targetEntity: Gyman\Bundle\VouchersBundle\Entity\Voucher
#      joinTable:
#        name: members_has_vouchers
#        joinColumns:
#          member_id:
#            referencedColumnName: id
#        inverseJoinColumns:
#          voucher_id:
#            referencedColumnName: id
#
#    entries:
#      targetEntity: Gyman\Bundle\VouchersBundle\Entity\Entry
#      joinTable:
#        name: members_has_entries
#        joinColumns:
#          member_id:
#            referencedColumnName: id
#        inverseJoinColumns:
#          entry_id:
#            referencedColumnName: id

  oneToOne:
    currentVoucher:
      targetEntity: Gyman\Bundle\VouchersBundle\Entity\Voucher
      joinColumn:
        name: current_voucher_id
        referencedColumnName: id
        onDelete: SET NULL
        nullable: true #false

#    lastEntry:
#      targetEntity: Gyman\Bundle\VouchersBundle\Entity\Entry
#      joinColumn:
#        name: last_entry_id
#        referencedColumnName: id
#        onDelete: SET NULL
#        nullable: true #false

  fields:
    nameSlug:
      name: name_slug
      type: string
      nullable: true
      gedmo:
        slug:
          fields: [ details.firstname, details.lastname]
          updatable: true
          separator: -
          unique: true

    deletedAt:
      name: deleted_at
      type: datetime
      nullable: true #false

    createdAt:
      name: created_at
      type: datetime
      nullable: true
      gedmo:
        timestampable:
          on: create

    updatedAt:
      name: updated_at
      type: datetime
      nullable: true
      gedmo:
        timestampable:
          on: update
