services:

  gyman.base.entity_manager:
    class: Gyman\Bundle\BaseBundle\EntityManager\BaseManager
    abstract: true
    arguments:
      - @doctrine.orm.default_entity_manager
      - @event_dispatcher
