services:
  gyman.settings.menu_builder:
      class: 'Gyman\Bundle\SettingsBundle\Menu\DefaultBuilder'
      arguments: ["@knp_menu.factory", "@security.authorization_checker"]

  gyman.settings.menu.main:
      class:            'Knp\Menu\MenuItem'
      factory:          ["@gyman.settings.menu_builder", "main"]
      tags:
          - { name: knp_menu.menu, alias: main }

  gyman.settings.club_settings_type:
    class: 'Gyman\Bundle\SettingsBundle\Form\Type\SettingsType'
    tags:
      - { name: form.type, alias: club_settings }

  gyman.settings.club_details_type:
    class: 'Gyman\Bundle\SettingsBundle\Form\Type\ClubDetailsType'
    tags:
      - { name: form.type, alias: club_details }

  gyman.settings.sections_type:
    class: 'Gyman\Bundle\SettingsBundle\Form\Type\SectionsType'
    tags:
      - { name: form.type, alias: club_sections }

  gyman.settings.sections_handler:
    class: 'Gyman\Application\Handler\UpdateSectionsHandler'
    arguments:
      - '@gyman.repository.section'
    tags:
      - { name: tactician.handler, command: 'Gyman\Application\Command\UpdateSectionsCommand'}