parameters:
    base_manager.class: Dende\DefaultBundle\Services\Manager\BaseManager
    voucher_entity.class: Dende\VouchersBundle\Entity\Voucher
    voucher_manager.class: Dende\VouchersBundle\Services\Manager\VoucherManager

services:
    base_manager:
        class:     "%base_manager.class%"
        calls:
             - [ setContainer, ["@service_container"] ]
    voucher_manager:
        class:          "%voucher_manager.class%"
        parent:         base_manager
        calls:
             - [ setClass, [%voucher_entity.class%] ]
    validator.voucher_date:
        class: Dende\VouchersBundle\Validator\Constraints\VoucherDateValidator
        arguments: [@doctrine.orm.entity_manager]
        tags:
            - { name: validator.constraint_validator, alias: validator.voucher_date_constraint}
            
#    validator.bp_invite_constraint:<
#        class: Remedy\PersonBundle\Constraint\BPInviteValidator
#        arguments: [@doctrine.orm.entity_manager]
#        tags:
#            - {name: validator.constraint_validator, alias: validator.bp_invite_constraint }<