parameters:
    base_manager.class: Dende\DefaultBundle\Services\Manager\BaseManager
    voucher_entity.class: Dende\VouchersBundle\Entity\Voucher
    voucher_manager.class: Dende\VouchersBundle\Services\Manager\VoucherManager
    date_validator.class: Dende\VouchersBundle\Validator\VoucherDateValidator
services:
    base_manager:
        class:     "%base_manager.class%"
        calls:
             - [ setContainer, ["@service_container"] ]

    voucher_manager:
        class:          "%voucher_manager.class%"
        parent:         base_manager
        calls:
             - [ setClass, [%voucher_entity.class%] ]

    validator.voucher_date:
        class:          "%date_validator.class%"
        arguments: 
            - "@voucher_manager"
        tags:
            - { name: validator.constraint_validator, alias: validator.voucher_date_constraint}