language: php

php:
  - 5.6

before_script:
  - phpenv config-add ./app/Resources/travis/php.ini
  - sudo add-apt-repository -y ppa:moti-p/cc
  - sudo apt-get update
  - sudo apt-get -y --reinstall install imagemagick
  - printf "\n" | pecl install imagick-beta
  - composer install -n

script:
 - ./bin/phpunit -c app
