Gyman\Domain\Calendar\Event\Occurrence:
  type: entity
  table: occurrences
  repositoryClass: Gyman\Bundle\AppBundle\Repository\OccurrenceRepository

  associationOverride:
    event:
      targetEntity: Gyman\Calendar\Domain\Calendar\EventInterface
      inversedBy: occurrences
      cascade: [all]
      joinColumns:
        EventId:
          name: event_id
          referencedColumnName: id

  oneToMany:
    entries:
      targetEntity: Gyman\Domain\Entry
      mappedBy: occurrence

  manyToOne:
    instructor:
      targetEntity: Gyman\Domain\User
      nullable: true

  embedded:
    subject:
      class: Gyman\Domain\Calendar\Event\Occurrence\Subject
      columnPrefix: subject_
    note:
      class: Gyman\Domain\Calendar\Event\Occurrence\Note
      columnPrefix: note_
