Gyman\Domain\Entry:
  type:   entity
  table:  entries
  repositoryClass:  Gyman\Bundle\AppBundle\Repository\EntryRepository

  id:
    id:
      type: uuid
      generator:
        strategy: CUSTOM
      customIdGenerator:
        class: Ramsey\Uuid\Doctrine\UuidGenerator

  embedded:
    price:
      class: Gyman\Domain\Entry\Price
      columnPrefix: price_

  manyToOne:
    member:
      targetEntity: Gyman\Domain\Member
      inversedBy: entries
      cascade: ["persist", "merge"]
      joinColumns:
        member_id:
          referencedColumnName: id
          unique: false
          onDelete: SET NULL
          onUpdate: RESTRICT

    voucher:
      targetEntity: Gyman\Domain\Voucher
      inversedBy: entries
      cascade: ["persist"]
      joinColumns:
        voucher_id:
          referencedColumnName: id
          unique: false
          onDelete: SET NULL
          onUpdate: RESTRICT

    occurrence:
      targetEntity: Gyman\Domain\Calendar\Event\Occurrence
      inversedBy: entries
      nullable: true
      orphanRemoval: false
      cascade: ["persist"]
      joinColumns:
        occurrence_id:
          referencedColumnName: id
          unique: false
          onDelete: SET NULL
          onUpdate: RESTRICT

  gedmo:
    soft_deleteable:
      field_name: deletedAt
      time_aware: false

  fields:
    startDate:
      type: datetime
      nullable: false

    endDate:
      type: datetime
      nullable: true

    type:
      type: string
      nullable: false

    deletedAt:
      name: deleted_at
      type: datetime
      nullable: true

    createdAt:
      name: created_at
      type: datetime
      nullable: false
      gedmo:
        timestampable:
          on: create

    updatedAt:
      name: updated_at
      type: datetime
      nullable: false
      gedmo:
        timestampable:
          on: update
