Gyman\Domain\User:
  type:   entity
  table:  users
  repositoryClass:  Gyman\Bundle\AppBundle\Repository\UserRepository

  id:
    id:
      type: uuid
      generator:
        strategy: CUSTOM
      customIdGenerator:
        class: Ramsey\Uuid\Doctrine\UuidGenerator

  oneToOne:
    member:
      targetEntity: Gyman\Domain\Member

  oneToMany:
    sections:
      targetEntity: Gyman\Domain\Section
      mappedBy:   instructor
      cascade: ["all"]

  fields:
    firstname:
      type: string
      length: 255
      nullable: true

    lastname:
      type: string
      length: 255
      nullable: true

    invitationToken:
      type: string
      length: 255
      nullable: true

    deletedAt:
      type: datetime
      nullable: true