Gyman\Domain\Voucher:
  type:   entity
  table:  vouchers
  repositoryClass:  Gyman\Bundle\AppBundle\Repository\VoucherRepository
  embedded:
    price:
      class: Gyman\Domain\Voucher\Price
      columnPrefix: price_

  id:
    id:
      type: guid
      generator: { strategy: UUID }

  gedmo:
    soft_deleteable:
      field_name: deletedAt
      time_aware: false

  manyToOne:
    member:
      targetEntity: Gyman\Domain\Member
      inversedBy: vouchers
      cascade: ["persist"]

  oneToMany:
    entries:
      targetEntity: Gyman\Domain\Entry
      mappedBy: voucher
      cascade: ["persist"]

  fields:
    startDate:
      type: datetime
      nullable: true #false

    endDate:
      type: datetime
      nullable: true

    maximumAmount:
      type: integer
      nullable: true

    deletedAt:
      name: deleted_at
      type: datetime
      nullable: true

    createdAt:
      name: created_at
      type: datetime
      nullable: true
      gedmo:
        timestampable:
          on: create

    updatedAt:
      name: updated_at
      type: datetime
      nullable: true
      gedmo:
        timestampable:
          on: update

    closedAt:
      name: closed_at
      type: datetime
      nullable: true
