<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'dende_calendar.update_strategy.single' shared service.

return $this->services['dende_calendar.update_strategy.single'] = new \Dende\Calendar\Application\Service\UpdateStrategy\Single();
