<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'fos_user.user_manager' shared service.

$this->services['fos_user.user_manager'] = $instance = new \Gyman\Bundle\AppBundle\EntityManager\UserManager(${($_ = isset($this->services['fos_user.util.password_updater']) ? $this->services['fos_user.util.password_updater'] : $this->getFosUser_Util_PasswordUpdaterService()) && false ?: '_'}, ${($_ = isset($this->services['fos_user.util.canonical_fields_updater']) ? $this->services['fos_user.util.canonical_fields_updater'] : $this->getFosUser_Util_CanonicalFieldsUpdaterService()) && false ?: '_'}, ${($_ = isset($this->services['fos_user.object_manager']) ? $this->services['fos_user.object_manager'] : $this->load(__DIR__.'/getFosUser_ObjectManagerService.php')) && false ?: '_'}, 'Gyman\\Domain\\User');

$instance->setSubdomainProvider($this->get($this->getParameter("subdomain_provider_service")));
$instance->setClubRepository(${($_ = isset($this->services['gyman.club.repository']) ? $this->services['gyman.club.repository'] : $this->getGyman_Club_RepositoryService()) && false ?: '_'});

return $instance;
