<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'gyman.app.command.clear_entries' shared service.

return $this->services['gyman.app.command.clear_entries'] = new \Gyman\Bundle\AppBundle\Command\CloseEntriesCommand(${($_ = isset($this->services['monolog.logger.commands']) ? $this->services['monolog.logger.commands'] : $this->load(__DIR__.'/getMonolog_Logger_CommandsService.php')) && false ?: '_'}, ${($_ = isset($this->services['debug.event_dispatcher']) ? $this->services['debug.event_dispatcher'] : $this->getDebug_EventDispatcherService()) && false ?: '_'});
