<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'gyman.members.create_user_for_member' shared service.

return $this->services['gyman.members.create_user_for_member'] = new \Gyman\Application\Handler\CreateUserForMemberHandler(${($_ = isset($this->services['gyman.user.repository']) ? $this->services['gyman.user.repository'] : $this->load(__DIR__.'/getGyman_User_RepositoryService.php')) && false ?: '_'}, ${($_ = isset($this->services['fos_user.util.user_manipulator']) ? $this->services['fos_user.util.user_manipulator'] : $this->load(__DIR__.'/getFosUser_Util_UserManipulatorService.php')) && false ?: '_'}, ${($_ = isset($this->services['fos_user.user_manager']) ? $this->services['fos_user.user_manager'] : $this->load(__DIR__.'/getFosUser_UserManagerService.php')) && false ?: '_'}, ${($_ = isset($this->services['debug.event_dispatcher']) ? $this->services['debug.event_dispatcher'] : $this->getDebug_EventDispatcherService()) && false ?: '_'});
