<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'gyman.listener.create_section_for_calendar' shared service.

return $this->services['gyman.listener.create_section_for_calendar'] = new \Gyman\Bundle\AppBundle\Listener\CreateSectionForCalendarListener(${($_ = isset($this->services['gyman.repository.section']) ? $this->services['gyman.repository.section'] : $this->load(__DIR__.'/getGyman_Repository_SectionService.php')) && false ?: '_'});
