<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'gyman.dashboard.menu_builder' shared service.

return $this->services['gyman.dashboard.menu_builder'] = new \Gyman\Bundle\DashboardBundle\Menu\Builder(${($_ = isset($this->services['knp_menu.factory']) ? $this->services['knp_menu.factory'] : $this->load(__DIR__.'/getKnpMenu_FactoryService.php')) && false ?: '_'}, ${($_ = isset($this->services['security.authorization_checker']) ? $this->services['security.authorization_checker'] : $this->getSecurity_AuthorizationCheckerService()) && false ?: '_'});
