<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'gyman.landing.form.registration' shared service.

return $this->services['gyman.landing.form.registration'] = new \Gyman\Bundle\LandingPageBundle\Form\CreateClubType();
