services:
    gyman.default.menu_builder:
        class: Gyman\Bundle\AppBundle\Menu\DefaultBuilder
        arguments: [@knp_menu.factory, @security.context]

    gyman.default.menu.main:
        class:            Knp\Menu\MenuItem
        factory_service:  gyman.default.menu_builder
        factory_method:   main
        arguments:        ["@request"]
        scope:            request
        tags:
            - { name: knp_menu.menu, alias: main }

    gyman.default.menu.profile:
        class: Knp\Menu\MenuItem
        factory_service: gyman.default.menu_builder
        factory_method: profile
        arguments: ["@request"]
        scope: request
        tags:
            - { name: knp_menu.menu, alias: profile }

    gyman.members.menu_builder:
      class: Gyman\Bundle\AppBundle\Menu\MemberBuilder
      arguments: [@knp_menu.factory, @security.context]

    gyman.landing.menu_builder:
      class: Gyman\Bundle\AppBundle\Menu\LandingBuilder
      arguments: [@knp_menu.factory]

    gyman.members.menu.tabs:
      class:            Knp\Menu\MenuItem
      factory_service:  gyman.members.menu_builder
      factory_method:   tabs
      scope:            request
      arguments:        [@request]
      tags:
          - { name: knp_menu.menu, alias: gyman.members.menu.tabs }

    gyman.landing.menu.tabs:
      class:            Knp\Menu\MenuItem
      factory_service:  gyman.landing.menu_builder
      factory_method:   tabs
      scope:            request
      arguments:        [@request]
      tags:
          - { name: knp_menu.menu, alias: gyman.landing.menu.tabs }

    gyman.members.menu.tabs_picture:
      class:            Knp\Menu\MenuItem
      factory_service:  gyman.members.menu_builder
      factory_method:   picture
      scope:            request
      tags:
          - { name: knp_menu.menu, alias: gyman.members.menu.tabs_picture }

#    gyman.default.menu_abstract:
#        abstract: true
#        class: Knp\Menu\MenuItem
#        factory_service: gyman.default.menu_builder
#        arguments: ["@request"]
#        scope: request
#
#    gyman.default.menu.profile:
#        parent: gyman.default.menu_abstract
#        tags:
#            - { name: knp_menu.menu, alias: main }
#
#    gyman.default.menu.profile:
#        parent: gyman.default.menu_abstract
#        tags:
#            - { name: knp_menu.menu, alias: main }
