---
services:

  gyman.repository.section:
    class:            Gyman\Bundle\AppBundle\Repository\SectionRepository
    factory_service:  doctrine.orm.tenant_entity_manager
    factory_method:   getRepository
    arguments:
      - 'Gyman\Domain\Section'

  gyman.vouchers.repository.entry:
    class:            Gyman\Bundle\AppBundle\Repository\EntryRepository
    factory_service:  doctrine.orm.tenant_entity_manager
    factory_method:   getRepository
    arguments:
      - 'Gyman\Domain\Entry'

  gyman.vouchers.repository:
    class:            Gyman\Bundle\AppBundle\Repository\VoucherRepository
    factory_service:  doctrine.orm.tenant_entity_manager
    factory_method:   getRepository
    arguments:
      - 'Gyman\Domain\Voucher'

  gyman.members.repository:
    class:            Gyman\Bundle\AppBundle\Repository\MemberRepository
    factory_method:   getRepository
    factory_service:  doctrine.orm.tenant_entity_manager
    arguments:
      - 'Gyman\Domain\Member'

  gyman.entries.repository:
    class:            Gyman\Bundle\AppBundle\Repository\EntryRepository
    factory_service:  doctrine.orm.tenant_entity_manager
    factory_method:   getRepository
    arguments:
      - 'Gyman\Domain\Entry'

  gyman.user.repository:
    class:            Gyman\Bundle\AppBundle\Repository\UserRepository
    factory:          ['@doctrine.orm.tenant_entity_manager', 'getRepository']
    arguments:
      - 'Gyman\Domain\User'

  gyman.occurrence.repository:
    class:            'Gyman\Bundle\AppBundle\Repository\OccurrenceRepository'
    factory:          ['@doctrine.orm.tenant_entity_manager', 'getRepository']
    arguments:
      - 'Gyman\Domain\Calendar\Event\Occurrence'

  gyman.event.repository:
    class:            'Gyman\Bundle\AppBundle\Repository\EventRepository'
    factory:          ['@doctrine.orm.tenant_entity_manager', 'getRepository']
    arguments:
      - 'Gyman\Domain\Calendar\Event'

  gyman.calendar.repository:
    class:            'Gyman\Bundle\AppBundle\Repository\EventRepository'
    factory:          ['@doctrine.orm.tenant_entity_manager', 'getRepository']
    arguments:
      - 'Gyman\Domain\Calendar'
