imports:
  - { resource: menu.yml }
  - { resource: services_app.yml }
  - { resource: services_vouchers.yml }
  - { resource: services_members.yml }
  - { resource: services_entries.yml }
  - { resource: services_admin.yml }

parameters:
  gyman.section_repository.class: Gyman\Bundle\AppBundle\Entity\SectionRepository

services:
  gyman.app.tenant_provider:
    class: Gyman\Bundle\AppBundle\Services\TenantProvider
    arguments:
      - @=service(parameter('subdomain_provider_service'))
      - @gyman.club.repository

  gyman.app.command.dump_hosts:
    class: Gyman\Bundle\AppBundle\Command\DumpHostsCommand
    tags:
      - {name: console.command}

  gyman.app.import_old_rio:
    class: Gyman\Bundle\AppBundle\Command\ImportOldRioCommand
    tags:
      - {name: console.command}

  gyman.listener.create_section_for_calendar:
    class: Gyman\Bundle\AppBundle\Listener\CreateSectionForCalendarListener
    arguments:
     - @gyman.repository.section
    tags:
      - {name: kernel.event_listener, method: onCalendarCreate, event: dende_calendar.calendar.after_creation}

  gyman.repository.section:
    class: %gyman.section_repository.class%
    factory_service: doctrine.orm.tenant_entity_manager
    factory_method: "getRepository"
    arguments: ["GymanAppBundle:Section"]