imports:
  - { resource: menu.yml }
  - { resource: services_app.yml }
  - { resource: services_vouchers.yml }
  - { resource: services_members.yml }
  - { resource: services_entries.yml }

services:
  gyman.app.command.dump_hosts:
    class: Gyman\Bundle\AppBundle\Command\DumpHostsCommand
    tags:
      - {name: console.command}