services:
  gyman.app.tenant_provider:
    class: Gyman\Bundle\AppBundle\Services\TenantProvider
    arguments:
      - @=service(parameter('subdomain_provider_service'))
      - @gyman.club.repository

  gyman.app.command.dump_hosts:
    class: Gyman\Bundle\AppBundle\Command\DumpHostsCommand
    tags:
      - {name: console.command}

  gyman.app.command.clear_entries:
    class: Gyman\Bundle\AppBundle\Command\CloseEntriesCommand
    calls:
      - [setLogger, ['@monolog.logger.commands']]
    tags:
      - {name: console.command}
      - {name: monolog.logger, channel: commands }

  gyman.app.command.clear_expired_vouchers:
    class: Gyman\Bundle\AppBundle\Command\ClearExpiredCurrentVouchersCommand
    calls:
      - [setLogger, ['@monolog.logger.commands']]
    tags:
      - {name: console.command}
      - {name: monolog.logger, channel: commands }

  gyman.app.command.update_current_voucher:
    class: Gyman\Bundle\AppBundle\Command\UpdateCurrentVoucherCommand
    calls:
      - [setLogger, ['@monolog.logger.commands']]
    tags:
      - {name: console.command}
      - {name: monolog.logger, channel: commands }

  gyman.listener.create_section_for_calendar:
    class: Gyman\Bundle\AppBundle\Listener\CreateSectionForCalendarListener
    arguments:
     - @gyman.repository.section
    tags:
      - {name: kernel.event_listener, method: onCalendarCreate, event: dende_calendar.calendar.after_creation}

  gyman.app.subdomain_provider:
    class: Gyman\Bundle\AppBundle\Services\SubdomainProvider
    arguments:
      - @request_stack
      - %base_url%

  gyman.app.test_subdomain_provider:
      class: Gyman\Bundle\AppBundle\Services\TestSubdomainProvider

  gyman.app.subdomain_name_lister:
    class: Gyman\Bundle\AppBundle\Listener\SubdomainNameListener
    arguments:
      - '@=service(parameter("subdomain_provider_service"))'
      - '@service_container'
      - '@twig'
    tags:
      - {name: kernel.event_listener, event: kernel.request, method: onKernelRequest }

  gyman.default.request.arraycollection_converter:
    class: Gyman\Bundle\AppBundle\Request\ArrayCollectionConverter
    calls:
      - [setEntityManager, [@doctrine.orm.tenant_entity_manager]]
    tags:
      - { name: request.param_converter}

  gyman.members.members_manager:
    class: %doctrine.orm.entity_manager.class%
    factory_service:  doctrine
    factory_method:   getEntityManager
    arguments: ["Member"]

  voucher_manager:
      class:          Gyman\Bundle\AppBundle\Services\Manager\VoucherManager
      parent:         gyman.base.entity_manager
      calls:
           - [ setClass, ['Gyman\Domain\Voucher'] ]
           - [ setEntityManager, ['@doctrine.orm.tenant_entity_manager']]

#  monolog.processor.sentry_context:
#      class: Gyman\Bundle\AppBundle\Monolog\SentryContextProcessor
#      arguments:  ["@security.token_storage"]
#      tags:
#          - { name: monolog.processor, method: processRecord, handler: sentry }