services:
  gyman.entries.entry_form_type:
    class: Gyman\Bundle\AppBundle\Form\EntryType
    arguments:
      - @dende_calendar.occurrences_repository
      - @gyman.repository.section
    tags:
      - { name: form.type, alias: gyman_entry_form }

  gyman.entries.repository:
    class:          Gyman\Domain\EntryRepository
    factory_service: doctrine.orm.tenant_entity_manager
    factory_method:  getRepository
    arguments:
      - Gyman\Domain\Entry

  gyman.entries.open_entry:
    class: Gyman\Application\Handler\OpenEntryHandler
    arguments:
      - @gyman.members.repository
      - @event_dispatcher

  gyman.entries.close_entry:
    class: Gyman\Application\Handler\CloseEntryHandler
    arguments:
      - @gyman.members.repository
      - @event_dispatcher

  gyman.entries.price_set_for_paid_entry.validator:
    class: Gyman\Bundle\AppBundle\Validator\PriceSetForPaidEntryValidator
    tags:
        - { name: validator.constraint_validator, alias: PriceSetForPaidEntryValidator }

  gyman.entries.only_enter_once.validator:
    class: Gyman\Bundle\AppBundle\Validator\OnlyEnterOnceValidator
    tags:
        - { name: validator.constraint_validator, alias: OnlyEnterOnceValidator }

  gyman.entries.cant_enter_past_occurrence.validator:
    class: Gyman\Bundle\AppBundle\Validator\CantEnterPastOccurrenceValidator
    tags:
        - { name: validator.constraint_validator, alias: CantEnterPastOccurrenceValidator }

  gyman.app.remove_entry_from_occurrence:
    class: Gyman\Bundle\AppBundle\Services\RemoveEntryFromOccurrence
    arguments:
      - @gyman.entries.repository
