imports:
  - { resource: menu.yml }
  - { resource: services_app.yml }
  - { resource: services_vouchers.yml }
  - { resource: services_members.yml }

services:
  gyman.default.request.arraycollection_converter:
    class: Gyman\Bundle\AppBundle\Request\ArrayCollectionConverter
    calls:
      - [setEntityManager, [@doctrine.orm.club_entity_manager]]
    tags:
      - { name: request.param_converter}
