services:
  gyman.app.subdomain_provider:
    class: Gyman\Bundle\AppBundle\Services\SubdomainProvider
    arguments:
      - @request_stack
      - %base_url%

  gyman.app.test_subdomain_provider:
      class: Gyman\Bundle\AppBundle\Services\TestSubdomainProvider

  gyman.app.subdomain_name_lister:
    class: Gyman\Bundle\AppBundle\Listener\SubdomainNameListener
    arguments:
      - @=service(parameter('subdomain_provider_service'))
      - @service_container
    tags:
      - {name: kernel.event_listener, event: kernel.request, method: onKernelRequest }

  gyman.default.request.arraycollection_converter:
    class: Gyman\Bundle\AppBundle\Request\ArrayCollectionConverter
    calls:
      - [setEntityManager, [@doctrine.orm.club_entity_manager]]
    tags:
      - { name: request.param_converter}

  gyman.app.club_settings_type:
    class: Gyman\Bundle\AppBundle\Form\SettingsType
    tags:
      - { name: form.type, alias: club_settings }