parameters:
    date_validator.class: Gyman\Bundle\AppBundle\Validator\VoucherDateValidator

imports:
  - { resource: menu.yml }

services:
  gyman.default.request.arraycollection_converter:
    class: Gyman\Bundle\AppBundle\Request\ArrayCollectionConverter
    calls:
      - [setEntityManager, [@doctrine.orm.club_entity_manager]]
    tags:
      - { name: request.param_converter}

  gyman.members.members_manager:
    class: %doctrine.orm.entity_manager.class%
    factory_service:  doctrine
    factory_method:   getEntityManager
    arguments: ["Member"]

  gyman.members.repository:
    class:  "Gyman\Bundle\AppBundle\Entity\MemberRepository"
    factory_method: getRepository
    factory_service: doctrine.orm.club_entity_manager
    arguments: ["Gyman\Bundle\AppBundle\Entity\Member"]

  gyman.members.member_form_type:
    class: Gyman\Bundle\AppBundle\Form\MemberType
    tags:
      - { name: form.type, alias: gyman_member_form }

  gyman.members.member_search_form_type:
    class: Gyman\Bundle\AppBundle\Form\SearchType
    tags:
      - { name: form.type, alias: gyman_member_search_form }

  gyman.members.upload_member_foto_handler:
    class: Gyman\Domain\Handler\UploadMemberFotoHandler
    arguments: [%galleryDirectory%]

  gyman.members.update_member:
    class: Gyman\Domain\Handler\UpdateMemberHandler
    arguments: [@gyman.members.repository, @gyman.members.upload_member_foto_handler, @event_dispatcher]

  gyman.members.create_member:
    class: Gyman\Domain\Handler\CreateMemberHandler
    arguments: [@gyman.members.repository, @gyman.members.upload_member_foto_handler, @event_dispatcher]

  gyman.members.unique_member_email.validator:
    class: Gyman\Bundle\AppBundle\Validator\UniqueMemberEmailValidator
    arguments: [@gyman.members.repository]
    tags:
        - { name: validator.constraint_validator, alias: UniqueMemberEmailValidator }

  gyman.members.unique_member_barcode.validator:
    class: Gyman\Bundle\AppBundle\Validator\UniqueMemberBarcodeValidator
    arguments: [@gyman.members.repository]
    tags:
        - { name: validator.constraint_validator, alias: UniqueMemberBarcodeValidator }

  gyman.vouchers.form.voucher:
    class: Gyman\Bundle\AppBundle\Form\VoucherType
    tags:
      - { name: form.type, alias: gyman_voucher_form }

  gyman.vouchers.create_voucher:
    class: Gyman\Domain\Handler\CreateVoucherHandler
    arguments:
      - @gyman.members.repository
      - @event_dispatcher

  gyman.vouchers.close_voucher:
    class: Gyman\Domain\Service\CloseVoucher
    arguments:
      - @gyman.vouchers.repository
      - @event_dispatcher

  gyman.vouchers.repository:
      class:          Gyman\Bundle\AppBundle\Entity\VoucherRepository
      factory_service: doctrine.orm.club_entity_manager
      factory_method:  getRepository
      arguments:
        - Gyman\Bundle\AppBundle\Entity\Voucher

  gyman.twig.voucher_extension:
      class: Gyman\Bundle\AppBundle\Twig\VoucherExtension
      calls:
        - [setTranslator, [@translator]]
      tags:
          - { name: twig.extension }

  gyman.vouchers.repository.entry:
    class:          Gyman\Bundle\AppBundle\Repository\EntryRepository
    factory_service: doctrine.orm.club_entity_manager
    factory_method:  getRepository
    arguments:
      - Gyman\Bundle\AppBundle\Entity\Entry

  voucher_manager:
      class:          Gyman\Bundle\AppBundle\Services\Manager\VoucherManager
      parent:         gyman.base.entity_manager
      calls:
           - [ setClass, [Gyman\Bundle\AppBundle\Entity\Voucher] ]
           - [ setEntityManager, [@doctrine.orm.club_entity_manager]]

  validator.voucher_date:
      class:          "%date_validator.class%"
      arguments:
          - "@voucher_manager"
      tags:
          - { name: validator.constraint_validator, alias: validator.voucher_date_constraint}
