services:

  gyman.members.members_manager:
    class: %doctrine.orm.entity_manager.class%
    factory_service:  doctrine
    factory_method:   getEntityManager
    arguments: ["Member"]

  gyman.members.repository:
    class:  "Gyman\Bundle\AppBundle\Repository\MemberRepository"
    factory_method: getRepository
    factory_service: doctrine.orm.tenant_entity_manager
    arguments: ["Gyman\Domain\Member"]

  gyman.members.member_form_type:
    class: Gyman\Bundle\AppBundle\Form\MemberType
    tags:
      - { name: form.type, alias: gyman_member_form }

  gyman.members.member_search_form_type:
    class: Gyman\Bundle\AppBundle\Form\SearchType
    tags:
      - { name: form.type, alias: gyman_member_search_form }

  gyman.members.upload_member_foto_handler:
    class: Gyman\Application\Handler\UploadMemberFotoHandler
    arguments:
      - %galleryDirectory%
      - @=service(parameter('subdomain_provider_service'))

  gyman.members.update_member:
    class: Gyman\Application\Handler\UpdateMemberHandler
    arguments: [@gyman.members.repository, @gyman.members.upload_member_foto_handler, @event_dispatcher]

  gyman.members.create_member:
    class: Gyman\Application\Handler\CreateMemberHandler
    arguments: [@gyman.members.repository, @gyman.members.upload_member_foto_handler, @event_dispatcher]

  gyman.members.unique_member_email.validator:
    class: Gyman\Bundle\AppBundle\Validator\UniqueMemberEmailValidator
    arguments: [@gyman.members.repository]
    tags:
        - { name: validator.constraint_validator, alias: UniqueMemberEmailValidator }

  gyman.members.unique_member_barcode.validator:
    class: Gyman\Bundle\AppBundle\Validator\UniqueMemberBarcodeValidator
    arguments: [@gyman.members.repository]
    tags:
        - { name: validator.constraint_validator, alias: UniqueMemberBarcodeValidator }
