services:
  gyman.vouchers.form.voucher:
    class: Gyman\Bundle\AppBundle\Form\VoucherType
    arguments:
      - @gyman.members.repository
    tags:
      - { name: form.type, alias: gyman_voucher_form }

  gyman.vouchers.create_voucher:
    class: Gyman\Application\Handler\CreateVoucherHandler
    arguments:
      - @gyman.members.repository
      - @event_dispatcher

  gyman.vouchers.close_voucher:
    class: Gyman\Domain\Service\CloseVoucher
    arguments:
      - @gyman.members.repository
      - @event_dispatcher

  gyman.vouchers.repository:
      class:          Gyman\Domain\VoucherRepository
      factory_service: doctrine.orm.tenant_entity_manager
      factory_method:  getRepository
      arguments:
        - Gyman\Domain\Voucher

  gyman.twig.voucher_extension:
      class: Gyman\Bundle\AppBundle\Twig\VoucherExtension
      calls:
        - [setTranslator, [@translator]]
      tags:
        - { name: twig.extension }

  gyman.vouchers.repository.entry:
    class:          Gyman\Domain\EntryRepository
    factory_service: doctrine.orm.tenant_entity_manager
    factory_method:  getRepository
    arguments:
      - Gyman\Domain\Entry

  voucher_manager:
      class:          Gyman\Bundle\AppBundle\Services\Manager\VoucherManager
      parent:         gyman.base.entity_manager
      calls:
           - [ setClass, [Gyman\Domain\Voucher] ]
           - [ setEntityManager, [@doctrine.orm.tenant_entity_manager]]

  validator.voucher_date:
      class:          Gyman\Bundle\AppBundle\Validator\VoucherDateValidator
      arguments:
          - "@voucher_manager"
      tags:
          - { name: validator.constraint_validator, alias: validator.voucher_date_constraint}

  gyman.app.validator.voucher_amount_for_credit_entries_constraint:
      class:          Gyman\Bundle\AppBundle\Validator\MaximumAmountGreaterThanCreditEntriesValidator
      tags:
          - { name: validator.constraint_validator, alias: validator.voucher_amount_for_credit_entries_constraint}
