---
services:

  gyman.twig.voucher_extension:
      class: Gyman\Bundle\AppBundle\Twig\VoucherExtension
      calls:
        - [setTranslator, ['@translator']]
      tags:
        - { name: twig.extension }


  gyman.app.twig.entries_extension:
    class: 'Gyman\Bundle\AppBundle\Twig\EntriesExtension'
    tags:
      - { name: twig.extension }
