---
services:
  validator.voucher_date:
    class:          Gyman\Bundle\AppBundle\Validator\VoucherDateValidator
    arguments:
        - "@voucher_manager"
    tags:
        - { name: validator.constraint_validator, alias: validator.voucher_date_constraint}

  gyman.app.validator.voucher_amount_for_credit_entries_constraint:
    class:          Gyman\Bundle\AppBundle\Validator\MaximumAmountGreaterThanCreditEntriesValidator
    tags:
        - { name: validator.constraint_validator, alias: validator.voucher_amount_for_credit_entries_constraint}

  gyman.members.unique_member_email.validator:
    class: Gyman\Bundle\AppBundle\Validator\UniqueMemberEmailValidator
    arguments: [@gyman.members.repository]
    tags:
        - { name: validator.constraint_validator, alias: UniqueMemberEmailValidator }

  gyman.members.unique_member_barcode.validator:
    class: Gyman\Bundle\AppBundle\Validator\UniqueMemberBarcodeValidator
    arguments: [@gyman.members.repository]
    tags:
        - { name: validator.constraint_validator, alias: UniqueMemberBarcodeValidator }

  gyman.entries.price_set_for_paid_entry.validator:
    class: Gyman\Bundle\AppBundle\Validator\PriceSetForPaidEntryValidator
    tags:
        - { name: validator.constraint_validator, alias: PriceSetForPaidEntryValidator }

  gyman.entries.only_enter_once.validator:
    class: Gyman\Bundle\AppBundle\Validator\OnlyEnterOnceValidator
    tags:
        - { name: validator.constraint_validator, alias: OnlyEnterOnceValidator }

  gyman.entries.cant_enter_past_occurrence.validator:
    class: Gyman\Bundle\AppBundle\Validator\CantEnterPastOccurrenceValidator
    tags:
        - { name: validator.constraint_validator, alias: CantEnterPastOccurrenceValidator }

  gyman.club.unique_subdomain.validator:
    class: Gyman\Bundle\AppBundle\Validator\UniqueClubSubdomainValidator
    arguments:
      - "@gyman.club.repository"
    tags:
        - { name: validator.constraint_validator, alias: UniqueClubSubdomainValidator }
