---
Gyman\Bundle\ClubBundle\Entity\Club:
  properties:
    name:
      - NotNull:
          groups: ['Default', 'createClub', 'updateClub']
    subdomain:
      - NotNull:
          groups: ['Default', 'createClub', 'updateClub']
      - Gyman\Bundle\AppBundle\Validator\UniqueClubSubdomain:
          groups: ['Default', 'createClub', 'updateClub']


