<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'gyman.entries.close_entry' shared service.

return $this->services['gyman.entries.close_entry'] = new \Gyman\Application\Handler\CloseEntryHandler(${($_ = isset($this->services['gyman.entries.repository']) ? $this->services['gyman.entries.repository'] : $this->load(__DIR__.'/getGyman_Entries_RepositoryService.php')) && false ?: '_'}, ${($_ = isset($this->services['debug.event_dispatcher']) ? $this->services['debug.event_dispatcher'] : $this->getDebug_EventDispatcherService()) && false ?: '_'});
