<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'gyman.settings.sections_type' shared service.

return $this->services['gyman.settings.sections_type'] = new \Gyman\Bundle\SettingsBundle\Form\Type\SectionsType();
