<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'dende_calendar.occurrences_provider' shared service.

return $this->services['dende_calendar.occurrences_provider'] = new \Dende\CalendarBundle\Service\OccurrencesProvider($this->get($this->getParameter("dende_calendar.occurrence_repository_service_name")), ${($_ = isset($this->services['router']) ? $this->services['router'] : $this->getRouterService()) && false ?: '_'}, 'dende_calendar_default_updateevent');
