<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'gyman.members.menu.tabs_picture' shared service.

return $this->services['gyman.members.menu.tabs_picture'] = ${($_ = isset($this->services['gyman.members.menu_builder']) ? $this->services['gyman.members.menu_builder'] : $this->load(__DIR__.'/getGyman_Members_MenuBuilderService.php')) && false ?: '_'}->picture();
