<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'gyman.reports.filter_date' shared service.

$this->services['gyman.reports.filter_date'] = $instance = new \Gyman\Bundle\ReportsBundle\Form\Type\DateFilterType();

$instance->setAvailableStrategies($this->parameters['available_reporting_strategies']);

return $instance;
