---
services:
  gyman.form.type.sections:
    class: Gyman\Bundle\AppBundle\Form\SectionsCollectionType
    arguments:
      - '@doctrine'
    tags:
      - { name: form.type, alias: sections }

  gyman.form.type.occurrences:
    class: Gyman\Bundle\AppBundle\Form\Occurrence\OccurrenceType
    arguments:
      - '@doctrine'
    tags:
      - { name: form.type, alias: occurrence }

  gyman.vouchers.form.voucher:
    class: Gyman\Bundle\AppBundle\Form\VoucherType
    arguments:
      - '@gyman.members.repository'
    tags:
      - { name: form.type, alias: gyman_voucher_form }

  gyman.vouchers.form.voucher_update:
    class: 'Gyman\Bundle\AppBundle\Form\UpdateVoucherType'
    arguments:
      - "@gyman.members.repository"
    tags:
      - { name: form.type, alias: gyman_voucher_update_form }

  gyman.form.member_update_form:
    class: Gyman\Bundle\AppBundle\Form\UpdateMemberType
    tags:
      - { name: form.type, alias: member }

  gyman.form.member_create_form:
    class: Gyman\Bundle\AppBundle\Form\CreateMemberType
    tags:
      - { name: form.type, alias: member }

  gyman.members.member_search_form_type:
    class: Gyman\Bundle\AppBundle\Form\SearchType
    tags:
      - { name: form.type, alias: gyman_member_search_form }

  gyman.entries.entry_form_type:
    class: Gyman\Bundle\AppBundle\Form\EntryType
    arguments:
      - '@gyman.occurrence.repository'
      - '@gyman.repository.section'
    tags:
      - { name: form.type, alias: gyman_entry_form }

  gyman.subdomain:
    class: Gyman\Bundle\AppBundle\Form\SubdomainType
    tags:
      - { name: form.type, alias: subdomain }

# REST FORMS

  gyman.rest.entries.entry_form_type:
    class: Gyman\Bundle\AppBundle\Form\Rest\EntryType
    tags:
      - { name: form.type, alias: gyman_entry_form_rest }
