---
services:

  gyman.members.query:
    class:          Gyman\Infrastructure\Query\MemberQuery
    arguments:
      - "@=service('doctrine.orm.tenant_entity_manager').getConnection()"

  gyman.entries.query:
    class:          Gyman\Infrastructure\Query\EntryQuery
    arguments:
      - "@=service('doctrine.orm.tenant_entity_manager').getConnection()"