imports:
  - { resource: forms.yml }
  - { resource: handlers.yml }
  - { resource: menu.yml }
  - { resource: repositories.yml }
  - { resource: twig_extensions.yml }
  - { resource: validators.yml }

services:
  gyman.app.tenant_provider:
    class: Gyman\Bundle\AppBundle\Services\TenantProvider
    arguments:
      - "@=service(parameter('subdomain_provider_service'))"
      - '@gyman.club.repository'
      - %database_host%
    tags:
      - {name: tenant_provider, connection_name: tenant}

  gyman.app.command.dump_hosts:
    class: Gyman\Bundle\AppBundle\Command\DumpHostsCommand
    tags:
      - {name: console.command}

  gyman.app.command.clear_entries:
    class: Gyman\Bundle\AppBundle\Command\CloseEntriesCommand
    arguments:
      - '@monolog.logger.commands'
      - '@event_dispatcher'
    tags:
      - {name: console.command}
      - {name: monolog.logger, channel: commands }

  gyman.app.command.clear_expired_vouchers:
    class: Gyman\Bundle\AppBundle\Command\ClearExpiredCurrentVouchersCommand
    calls:
      - [setLogger, ['@monolog.logger.commands']]
    tags:
      - {name: console.command}
      - {name: monolog.logger, channel: commands }

  gyman.app.command.update_current_voucher:
    class: Gyman\Bundle\AppBundle\Command\UpdateCurrentVoucherCommand
    calls:
      - [setLogger, ['@monolog.logger.commands']]
    tags:
      - {name: console.command}
      - {name: monolog.logger, channel: commands }

  gyman.app.subdomain_provider:
    class: Gyman\Bundle\AppBundle\Services\SubdomainProvider
    arguments:
      - '@request_stack'
      - '%base_url%'

  gyman.app.globals_factory:
    class: Gyman\Bundle\AppBundle\GlobalsFactory
    arguments:
      - '@gyman.app.subdomain_provider'
    calls:
      - [setUp, []]

  gyman.app.test_subdomain_provider:
      class: Gyman\Bundle\AppBundle\Services\TestSubdomainProvider

  gyman.app.subdomain_name_listener:
    class: Gyman\Bundle\AppBundle\Listener\SubdomainNameListener
    arguments:
      - '@=service(parameter("subdomain_provider_service"))'
      - '@dende_multitenancy.tenant_manager'
      - '@router'
    tags:
      - {name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: 1000 }

  gyman.app.listener.redirect_to_404:
    class: Gyman\Bundle\AppBundle\Listener\RedirectTo404IfClubNotExists
    arguments:
      - '@router'
    tags:
      - {name: kernel.event_listener, event: kernel.exception, method: onException }

  gyman.app.listener.setup_club_paths:
    class: Gyman\Bundle\AppBundle\Listener\SetupPathsForClub
    arguments:
      - '@gyman.club.repository'
      - '@twig'
      - { no_image: %no_image%, gallerydirectory: %gallerydirectory%, gallerypath: %gallerypath%, env: %kernel.environment% }
    tags:
      - {name: kernel.event_listener, event: multitenancy.post_switch_connection, method: onKernelRequest }

  gyman.default.request.arraycollection_converter:
    class: Gyman\Bundle\AppBundle\Request\ArrayCollectionConverter
    calls:
      - [setEntityManager, ['@doctrine.orm.tenant_entity_manager']]
    tags:
      - { name: request.param_converter}

  gyman.members.members_manager:
    class: %doctrine.orm.entity_manager.class%
    factory_service:  doctrine
    factory_method:   getEntityManager
    arguments: ["Member"]

  voucher_manager:
      class:          Gyman\Bundle\AppBundle\Services\Manager\VoucherManager
      parent:         gyman.base.entity_manager
      calls:
           - [ setClass, ['Gyman\Domain\Voucher'] ]
           - [ setEntityManager, ['@doctrine.orm.tenant_entity_manager']]

  gyman.tab_chooser:
    class: Gyman\Bundle\AppBundle\Menu\TabChooserService
    arguments:
      - "@request_stack"