<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'account_bundle.registered_user_subscriber' shared service.

$this->services['account_bundle.registered_user_subscriber'] = $instance = new \Gyman\Bundle\AccountBundle\Service\Subscriber\RegisteredUserSubscriber();

$instance->setRouter(${($_ = isset($this->services['router']) ? $this->services['router'] : $this->getRouterService()) && false ?: '_'});
$instance->setSession(${($_ = isset($this->services['session']) ? $this->services['session'] : $this->load(__DIR__.'/getSessionService.php')) && false ?: '_'});
$instance->setMailer(${($_ = isset($this->services['mailer.registration_successful']) ? $this->services['mailer.registration_successful'] : $this->load(__DIR__.'/getMailer_RegistrationSuccessfulService.php')) && false ?: '_'});

return $instance;
