<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'dende_calendar.handler.create_event' shared service.

return $this->services['dende_calendar.handler.create_event'] = new \Dende\Calendar\Application\Handler\CreateEventHandler(${($_ = isset($this->services['dende_calendar.calendar_repository']) ? $this->services['dende_calendar.calendar_repository'] : $this->load(__DIR__.'/getDendeCalendar_CalendarRepositoryService.php')) && false ?: '_'}, $this->get($this->getParameter("dende_calendar.event_repository_service_name")), $this->get($this->getParameter("dende_calendar.occurrence_repository_service_name")), $this->get($this->getParameter("dende_calendar.event_factory_service_name")), $this->get($this->getParameter("dende_calendar.occurrence_factory_service_name")));
