<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'liip_monitor.helper.runner_manager' shared service.

return $this->services['liip_monitor.helper.runner_manager'] = new \Liip\MonitorBundle\Helper\RunnerManager($this);
