<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'gyman.vouchers.form.voucher_update' shared service.

return $this->services['gyman.vouchers.form.voucher_update'] = new \Gyman\Bundle\AppBundle\Form\UpdateVoucherType(${($_ = isset($this->services['gyman.members.repository']) ? $this->services['gyman.members.repository'] : $this->load(__DIR__.'/getGyman_Members_RepositoryService.php')) && false ?: '_'});
