<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'liip_monitor.runner_default' shared service.

return $this->services['liip_monitor.runner_default'] = new \Liip\MonitorBundle\Runner();
