parameters:
  session_lifetime: 86400 # 24 hours
  no_image: /bundles/default/images/no-profile.gif

imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: fos_user.yml }
    - { resource: "@MembersBundle/Resources/config/services.yml" }

framework:
    translator:      { fallback: %locale% }
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_proxies: ~
    session:
        cookie_lifetime:  %session_lifetime%
        gc_maxlifetime: 1800
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%
    globals:
      sentry_url:     %sentry_url%
    form:
        resources:
            - ::fields.html.twig

doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8
        mapping_types:
            enum: string
    orm:
        auto_generate_proxy_classes: %kernel.debug%
#        auto_mapping: true
#        mappings:
#            StofDoctrineExtensionsBundle: ~
        entity_managers:
            default:
                dql:
                    datetime_functions:
                        dayname: Gyman\Bundle\MembersBundle\DQL\Dayname
                auto_mapping: true
                filters:
                    softdeleteable:
                        class: Gedmo\SoftDeleteable\Filter\SoftDeleteableFilter
                        enabled: true
                mappings:
                    StofDoctrineExtensionsBundle: ~

swiftmailer:
    transport: smtp
    host:      smtp.gmail.com
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    port:                 465
    encryption:           ssl
    auth_mode:            ~
    
    logging:        true

oneup_uploader:
    mappings:
        gallery:
            frontend: custom
            custom_frontend:
                class: Gyman\Bundle\MembersBundle\Controller\UploadController
                name: MyFancyCustomUploader            
                
default:
    noImage:                %no_image%
    galleryDir:             /uploads/gallery/
    
stof_doctrine_extensions:
    default_locale: en_US
    orm:
        default:
            timestampable: true
            sluggable: true
            
fos_js_routing:
    routes_to_expose: [.*]
    
monolog:  
    handlers:  
        main:
            type:  stream  
            path:  %kernel.logs_dir%/%kernel.environment%.log  
            level: error

fos_rest:
    routing_loader:
        default_format: json
        include_format: false

doctrine_migrations:
    dir_name: %kernel.root_dir%/Migrations
    namespace: Application\Migrations
    table_name: migration_versions
    name: Application Migrations

