parameters:
  session_lifetime: 86400 # 24 hours
  no_image: /bundles/default/images/no-profile.gif
  gallery_dir: /uploads/gallery/
  revision_file: "%kernel.root_dir%/../REVISION"

imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: fos_user.yml }
    - { resource: timeline.yml }
    - { resource: doctrine.yml }

framework:
    translator:      { fallback: %locale% }
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enabled: true, enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        cookie_lifetime:  %session_lifetime%
        gc_maxlifetime: 1800
        handler_id:  ~

    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%
    globals:
      sentry_url:     %sentry_url%
      gallery_dir:    %gallery_dir%
    form:
        resources:
            - ::fields.html.twig

swiftmailer:
    transport: smtp
    host:      smtp.gmail.com
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    port:                 465
    encryption:           ssl
    auth_mode:            ~
    
    logging:        true

oneup_uploader:
    mappings:
        gallery:
            frontend: custom
            custom_frontend:
                class: Gyman\Bundle\MembersBundle\Controller\UploadController
                name:  MyFancyCustomUploader
                
default:
    noImage:                %no_image%
    galleryDir:             %gallery_dir%
    
stof_doctrine_extensions:
    default_locale: pl_PL
    orm:
        default:
            timestampable: true
            sluggable: true
        club:
            timestampable: true
            sluggable: true

fos_js_routing:
    routes_to_expose: [.*]
    
monolog:  
  handlers:
    main:
      type:  stream
      path:  %kernel.logs_dir%/%kernel.environment%.log
      level: error

jms_serializer:
  handlers:
    datetime:
      default_format: "Y-m-d H:i:s"
      default_timezone: "UTC"
  metadata:
    auto_detection: true

fos_rest:
  param_fetcher_listener: true
  body_listener:
    decoders:
      json: fos_rest.decoder.jsontoform
  format_listener: true
  view:
    view_response_listener: force
    serialize_null: true
    failed_validation: 422
  routing_loader:
      default_format: json
      include_format: false

sensio_framework_extra:
  view: { annotations: false }
  router: { annotations: true }
  request: { converters: true }

knp_time: ~

nelmio_api_doc: ~

doctrine_migrations:
    dir_name: %kernel.root_dir%/../src/Gyman/MainBundle/DoctrineMigrations
    namespace: Gyman\MainBundle\DoctrineMigrations
    table_name: doctrine_migrations
    name: Gyman DB Migrations

accelerator_cache:
    host: %base_url%
    web_dir: %kernel.root_dir%/../web
