imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: fos_user.yml }
    - { resource: doctrine.yml }
    - { resource: "@AdminBundle/Resources/config/services.yml" }

parameters:
  date_format: "Y.m.d"
  time_format: "H:i:s"
  datetime_format: "Y.m.d H:i:s"

  session_lifetime: 86400 # 24 hours
  no_image: "/bundles/gymanapp/images/no-profile.gif"

  galleryDirectory: '%kernel.root_dir%/../web/uploads/gallery/'
  galleryPath: '/uploads/gallery/'

  revision_file: "%kernel.root_dir%/../REVISION"
  memcached.servers:
    - { host: 127.0.0.1, port: 11211 }

  subdomain_provider_service: gyman.app.subdomain_provider

  resolved_occurrence_class: 'Gyman\Domain\Calendar\Event\Occurrence'
  dende_calendar.occurrences_repository.class:  'Gyman\Bundle\AppBundle\Repository\OccurrenceRepository'

services:
    fos_user.doctrine_registry:
        alias: doctrine

    memcached:
        class: Memcached
        calls:
            - [ addServers, [ '%memcached.servers%' ]]

sentry:
    dsn: "%sentry_url%"
    release: "%sentry_revision%"

framework:
    ide: "phpstorm://%%f:%%l"
    translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enabled: true, enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        cookie_lifetime:  "%session_lifetime%"
        gc_maxlifetime: 1800
        handler_id:  ~
#    assets:
#        json_manifest_path: '%kernel.root_dir%/../public/build/manifest.json'
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
  form_themes:
    - ::fields.html.twig
  debug:                  "%kernel.debug%"
  strict_variables:       false # %kernel.debug%
  globals:
    sentry_url:           "%sentry_url%"
    gallery_dir:          "%galleryPath%"
    google_maps_api_key:  "%google_maps_api_key%"
    baseUrl:              "%base_url%"

swiftmailer:
    transport:            "%mailer_transport%"
    host:                 "%mailer_host%"
    port:                 "%mailer_port%"
    username:             "%mailer_user%"
    password:             "%mailer_password%"

    logging:              true

    spool:
        type:             file
        path:             '%kernel.root_dir%/spool'

#oneup_uploader:
#    mappings:
#        gallery:
#            frontend: custom
#            custom_frontend:
#                class: Gyman\Bundle\AppBundle\Controller\UploadController
#                name:  MyFancyCustomUploader
                
gyman_app:
  schedule_generator:
    phantom_path:           '%kernel.root_dir%/../node_modules/.bin/phantomjs'
    rasterize_script_path:  '%kernel.root_dir%/../node_modules/phantomjs/lib/phantom/examples/rasterize.js'
    destination_directory:  '%kernel.root_dir%/../web/schedules/'
    filename:               'schedule.png'

dende_calendar:
  model_manager_name:                   'tenant'
  backend_type:                         'ORM'
  calendar_repository_service_name:     'gyman.calendar.repository'
  calendar_factory_service_name:        'gyman.calendar.factory'
  event_repository_service_name:        'gyman.event.repository'
  event_factory_service_name:           'gyman.event.factory'
  occurrence_repository_service_name:   'gyman.occurrence.repository'
  occurrence_factory_service_name:      'gyman.occurrence.factory'
  occurrence_class:                     Gyman\Domain\Calendar\Event\Occurrence
  mapping:
    event:
      entity:                             Dende\Calendar\Domain\Calendar\Event
      map:
        bundle:                           Dende\Calendar\Domain\Calendar\Event
        app:                              Gyman\Domain\Calendar\Event
    calendar:
      entity:                             Dende\Calendar\Domain\Calendar
      map:
        bundle:                           Dende\Calendar\Domain\Calendar
        app:                              Gyman\Domain\Calendar

dende_multitenancy:
  patched_commands:
    - "doctrine:*"
    - "fos:*"
    - "gyman:entries:close_expired"
    - "gyman:vouchers:*"
    - "gyman:calendar:*"

  connections:
    tenant:
      command_parameter_name:         club
      command_parameter_description:  Provide club name for tenant connection

#fos_js_routing:
#    routes_to_expose: [.*]
    
monolog:
  handlers:
    main:
      type:         fingers_crossed
      action_level: error
      handler:      grouped_main

    streamed_main:
      type:  stream
      path:  "%kernel.logs_dir%/%kernel.environment%.log"
      level: error
      channels: ['app']

    commands:
      type:  stream
      path:  "%kernel.logs_dir%/commands_%kernel.environment%.log"
      level: debug
      channels: ['commands']

    createNewClub:
      type:  stream
      path:  "%kernel.logs_dir%/create_club.log"
      level: debug
      channels: ['createNewClub']

    # Groups
    grouped_main:
      type:    group
      members: [streamed_main]

#jms_serializer:
#  handlers:
#    datetime:
#      default_format: "Y-m-d H:i:s"
#      default_timezone: "Europe/Warsaw"
#  metadata:
#    cache: true
#    auto_detection: false
#    directories:
##      app:
##        namespace_prefix: 'Gyman\Domain\Entity'
##        path:             '@GymanAppBundle/Resources/config/serializer/app'
#      domain:
#        namespace_prefix: 'Gyman\Domain'
#        path:             '@GymanAppBundle/Resources/config/serializer'
#      calendar:
#        namespace_prefix: 'Dende\Calendar\Domain'
#        path:             '@GymanAppBundle/Resources/config/serializer/calendar'

sensio_framework_extra:
    router:      { annotations: true }
    request:     { converters: true, auto_convert: true }
    view:        { annotations: true }
    cache:       { annotations: true }
    security:    { annotations: true }
    psr_message: { enabled: false }

#knp_time: ~

#liip_monitor:
#    mailer:
#        enabled:              false
#        recipient:            uirapuruadg@gmail.com
#        sender:               gyman.pl@gmail.com
#        subject:              "Health check"
#        send_on_warning:      true
#    checks:
#        php_extensions: [imagick, intl, mcrypt, json]
#        php_version:
#          5.6.0: ">="
##        disk_usage:
##          warning:              70
##          critical:             90
##          path:                 '%kernel.cache_dir%'
#        symfony_requirements:
#            file:                 '%kernel.root_dir%/SymfonyRequirements.php'
#        doctrine_dbal:
#          - default
##          - tenant
#        security_advisory:
#          lock_file:            '%kernel.root_dir%/../composer.lock'

knp_paginator:
    page_range: 5
    default_options:
        page_name: page                 # page query parameter name
        sort_field_name: sort           # sort field query parameter name
        sort_direction_name: direction  # sort direction query parameter name
        distinct: true                  # ensure distinct results, useful when ORM queries are using GROUP BY statements
        filter_field_name: filterField  # filter field query parameter name
        filter_value_name: filterValue  # filter value query paameter name
    template:
        pagination:   '@KnpPaginator/Pagination/twitter_bootstrap_pagination.html.twig'     # sliding pagination controls template
        sortable:     '@KnpPaginator/Pagination/sortable_link.html.twig' # sort link template
        filtration:   '@KnpPaginator/Pagination/filtration.html.twig'  # filters template