imports:
    - { resource: config_dev.yml }

parameters:
    translator.class: Gyman\Bundle\AppBundle\Translator\NoTranslator
    subdomain_provider_service: gyman.app.test_subdomain_provider

framework:
    test: ~
    session:
        storage_id: session.storage.filesystem
    profiler:
        collect: true
        only_exceptions: false

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true

doctrine:
  dbal:
    default_connection: default
    connections:
        default:
          driver:   pdo_sqlite
          dbname:   %database_name%
          path:     %kernel.cache_dir%/default.db

        tenant:
          driver:   pdo_sqlite
#          driver:   pdo_mysql
          dbname:   %database_name%_dende
#          user:     %database_user%
#          password: %database_password%
          path:     %kernel.cache_dir%/club.db
          memory: false

liip_functional_test:
  cache_sqlite_db: true
  authentication:
    username: %sqlite_database_user%
    password: %sqlite_database_password%

security:
    firewalls:
        main:
            http_basic: ~

monolog:
  handlers:
    main:
      type: stream
      path: "%kernel.logs_dir%/%kernel.environment%.log"
      level: ERROR