parameters:
  date_format: "Y.m.d"
  time_format: "H:i:s"
  datetime_format: "Y.m.d H:i:s"

  session_lifetime: 86400 # 24 hours
  no_image: /bundles/gymanapp/images/no-profile.gif

  galleryDirectory: %kernel.root_dir%/../web/uploads/gallery/
  galleryPath: /uploads/gallery/

  revision_file: "%kernel.root_dir%/../REVISION"
  memcached.servers:
    - { host: 127.0.0.1, port: 11211 }

  subdomain_provider_service: gyman.app.subdomain_provider

services:
#    globals_object:
#      class: Gyman\Bundle\AppBundle\Globals
#      calls:
#        - [setDefaultDateFormat, [%date_format%]]
#        - [setDefaultDateTimeFormat, [%datetime_format%]]

    memcached:
        class: Memcached
        calls:
            - [ addServers, [ %memcached.servers% ]]

    gedmo.listener.softdeleteable:
        class: Gedmo\SoftDeleteable\SoftDeleteableListener
        tags:
            - { name: doctrine.event_subscriber, connection: default }
            - { name: doctrine.event_subscriber, connection: club }
        calls:
            - [ setAnnotationReader, [ @annotation_reader ] ]

    data_fixture_loader:
        class: Gyman\Bundle\TestBundle\Services\FixtureLoader
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@symfony.data_fixtures.loader'

    symfony.data_fixtures.loader:
        public: false
        class: Symfony\Bridge\Doctrine\DataFixtures\ContainerAwareLoader
        arguments:
            - '@service_container'

imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: fos_user.yml }
#    - { resource: timeline.yml }
    - { resource: doctrine.yml }

framework:
    translator:      { fallback: %locale% }
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enabled: true, enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        cookie_lifetime:  %session_lifetime%
        gc_maxlifetime: 1800
        handler_id:  ~

    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%
    globals:
      sentry_url:     %sentry_url%
      gallery_dir:    %galleryPath%
    form:
        resources:
            - ::fields.html.twig

swiftmailer:
    transport: smtp
    host:      smtp.gmail.com
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    port:                 465
    encryption:           ssl
    auth_mode:            ~
    
    logging:        true

#oneup_uploader:
#    mappings:
#        gallery:
#            frontend: custom
#            custom_frontend:
#                class: Gyman\Bundle\AppBundle\Controller\UploadController
#                name:  MyFancyCustomUploader
                
gyman_app: ~

dende_calendar:
  entity_manager: club

stof_doctrine_extensions:
    default_locale: pl_PL
    orm:
        default:
            timestampable: true
            sluggable: true
        club:
            timestampable: true
            sluggable: true

fos_js_routing:
    routes_to_expose: [.*]
    
monolog:  
  handlers:
    main:
      type:  stream
      path:  %kernel.logs_dir%/%kernel.environment%.log
      level: error

jms_serializer:
  handlers:
    datetime:
      default_format: "Y-m-d H:i:s"
      default_timezone: "Europe/Warsaw"
  metadata:
    auto_detection: true
    directories:
      Domain:
        namespace_prefix: "Dende\\Calendar\\Domain"
        path: "%kernel.root_dir%/../../Resources/config/serializer/"

fos_rest:
  param_fetcher_listener: true
  body_listener:
    decoders:
      json: fos_rest.decoder.jsontoform
  format_listener: true
  view:
    view_response_listener: force
    serialize_null: true
    failed_validation: 422
  routing_loader:
      default_format: json
      include_format: false

sensio_framework_extra:
  view: { annotations: false }
  router: { annotations: true }
  request: { converters: true }

knp_time: ~
nelmio_api_doc: ~
accelerator_cache:
    host: %base_url%
    web_dir: %kernel.root_dir%/../web

bazinga_hateoas:
  metadata:
    cache:                file
    file_cache:
      dir:              %kernel.cache_dir%/hateoas
