parameters:
  date_format: "Y.m.d"
  time_format: "H:i:s"
  datetime_format: "Y.m.d H:i:s"

  session_lifetime: 86400 # 24 hours
  no_image: /bundles/gymanapp/images/no-profile.gif

  galleryDirectory: '%kernel.root_dir%/../web/uploads/gallery/'
  galleryPath: '/uploads/gallery/'

  revision_file: "%kernel.root_dir%/../REVISION"
  memcached.servers:
    - { host: 127.0.0.1, port: 11211 }

  subdomain_provider_service: gyman.app.subdomain_provider

services:
    fos_user.doctrine_registry:
        alias: doctrine

    memcached:
        class: Memcached
        calls:
            - [ addServers, [ '%memcached.servers%' ]]

    gedmo.listener.softdeleteable:
        class: Gedmo\SoftDeleteable\SoftDeleteableListener
        tags:
            - { name: doctrine.event_subscriber, connection: default }
            - { name: doctrine.event_subscriber, connection: tenant }
        calls:
            - [ setAnnotationReader, [ '@annotation_reader' ] ]

    data_fixture_loader:
        class: Gyman\Bundle\TestBundle\Services\FixtureLoader
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@symfony.data_fixtures.loader'

    symfony.data_fixtures.loader:
        public: false
        class: Symfony\Bridge\Doctrine\DataFixtures\ContainerAwareLoader
        arguments:
            - '@service_container'

imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: fos_user.yml }
    - { resource: doctrine.yml }

framework:
    ide: "phpstorm://%%f:%%l"
    translator:      { fallback: %locale% }
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enabled: true, enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        cookie_lifetime:  %session_lifetime%
        gc_maxlifetime: 1800
        handler_id:  ~

    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: false # %kernel.debug%
    globals:
      sentry_url:     %sentry_url%
      gallery_dir:    %galleryPath%
      google_maps_api_key: %google_maps_api_key%
    form:
        resources:
            - ::fields.html.twig

swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    port:      "%mailer_port%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"

    logging:        true

    spool:
        type: file
        path: '%kernel.root_dir%/spool'

#oneup_uploader:
#    mappings:
#        gallery:
#            frontend: custom
#            custom_frontend:
#                class: Gyman\Bundle\AppBundle\Controller\UploadController
#                name:  MyFancyCustomUploader
                
gyman_app: ~

dende_calendar:
  model_manager_name:   tenant
  backend_type:         ORM

dende_multidatabase:
  provider:                 gyman.app.tenant_provider
  connection:               doctrine.dbal.tenant_connection
  entity_manager:           doctrine.orm.tenant_entity_manager
  parameter_name:           club
  parameter_description:    Club subdomain's name
  commands:
    - doctrine:schema:update
    - doctrine:schema:create
    - doctrine:schema:drop
    - doctrine:fixtures:load
    - gyman:entries:close_expired
    - gyman:vouchers:clear_expired
    - gyman:vouchers:update_current
    - doctrine:migrations:diff
    - doctrine:migrations:execute
    - doctrine:migrations:generate
    - doctrine:migrations:migrate
    - doctrine:migrations:version
    - doctrine:migrations:status

  fixtures:
    default:
        - src/Gyman/Bundle/ClubBundle/DataFixtures/StandardConnection
    tenant:
        - src/Gyman/Bundle/AppBundle/DataFixtures/Club

stof_doctrine_extensions:
    default_locale: pl_PL
    orm:
        default:
            timestampable: true
            sluggable: true
        tenant:
            timestampable: true
            sluggable: true

fos_js_routing:
    routes_to_expose: [.*]
    
monolog:
  handlers:
    main:
      type:         fingers_crossed
      action_level: error
      handler:      grouped_main

    streamed_main:
      type:  stream
      path:  %kernel.logs_dir%/%kernel.environment%.log
      level: error
      channels: ['app']

    sentry:
      type:  raven
      dsn:   'http://c74d588fdca1443381fc0cf36d79ccf9:ce62521bf0a54c03b7304c067e7e59bf@gyman.pl:9000/2'
      level: error

    commands:
      type:  stream
      path:  %kernel.logs_dir%/commands_%kernel.environment%.log
      level: debug
      channels: ['commands']

    # Groups
    grouped_main:
      type:    group
      members: [sentry, streamed_main]

jms_serializer:
  handlers:
    datetime:
      default_format: "Y-m-d H:i:s"
      default_timezone: "Europe/Warsaw"
  metadata:
    cache: true
    auto_detection: false
    directories:
      app:
        namespace_prefix: Gyman\Domain\Entity
        path:             @GymanAppBundle/Resources/config/serializer/app
      domain:
        namespace_prefix: Gyman\Domain\Model
        path:             @GymanAppBundle/Resources/config/serializer/domain
      calendar:
        namespace_prefix: Dende\Calendar\Domain
        path:             @GymanAppBundle/Resources/config/serializer/calendar

fos_rest:
  param_fetcher_listener: true
  body_listener:
    decoders:
      json: fos_rest.decoder.jsontoform
  format_listener: true
  view:
    view_response_listener: force
    serialize_null: true
    failed_validation: 422
  routing_loader:
      default_format: json
      include_format: false

sensio_framework_extra:
    router:      { annotations: true }
    request:     { converters: true, auto_convert: true }
    view:        { annotations: true }
    cache:       { annotations: true }
    security:    { annotations: true }
    psr_message: { enabled: false }

knp_time: ~

nelmio_api_doc: ~

accelerator_cache:
    host: %base_url%
    web_dir: %kernel.root_dir%/../web

bazinga_hateoas:
  metadata:
    cache:                file
    file_cache:
      dir:              %kernel.cache_dir%/hateoas