doctrine:
    dbal:
      default_connection: default
      connections:
        default:
          driver:   %database_driver%
          host:     %database_host%
          port:     %database_port%
          dbname:   %database_name%
          user:     %database_user%
          password: %database_password%
          charset:  UTF8
          server_version: "5.6"
          mapping_types:
              enum: string
        club:
          driver:   %database_driver%
          host:     %database_host%
          port:     %database_port%
          platform_service: ~
          server_version: "5.6"
          dbname:   ~
          user:     ~
          password: ~
          charset:  UTF8
          wrapper_class: Gyman\Bundle\MultiDatabaseBundle\Connection\ConnectionWrapper
          mapping_types:
              enum: string
    orm:

        auto_generate_proxy_classes: %kernel.debug%
        default_entity_manager:   default

        entity_managers:
          default:
            metadata_cache_driver: apc
            result_cache_driver: apc
            query_cache_driver: apc

            auto_mapping: false # disabled so we can assign entities to our own connections
            connection:       default
            dql:
                string_functions:
                    multi_concat: Spy\TimelineBundle\Driver\Doctrine\AST\Functions\MultiConcatFunction
                datetime_functions:
                    dayname: Gyman\Bundle\MembersBundle\DQL\Dayname
            filters:
                softdeleteable:
                    class: Gedmo\SoftDeleteable\Filter\SoftDeleteableFilter
                    enabled: true
            mappings:
                StofDoctrineExtensionsBundle: ~
                UserBundle: ~
                ClubBundle: ~

          club:
            metadata_cache_driver: apc
            result_cache_driver: apc
            query_cache_driver: apc

            auto_mapping:     false # disabled so we can assign entities to our own connections
            connection:       club
            mappings:
              StofDoctrineExtensionsBundle: ~
              MembersBundle: ~
              VouchersBundle: ~
              FiltersBundle: ~
#              EntriesBundle: ~
              ScheduleBundle: ~
              SectionBundle: ~
              TimelineBundle: ~
              SpyTimelineBundle: ~
            dql:
                string_functions:
                    multi_concat: Spy\TimelineBundle\Driver\Doctrine\AST\Functions\MultiConcatFunction
                datetime_functions:
                    dayname: Gyman\Bundle\MembersBundle\DQL\Dayname
            filters:
                softdeleteable:
                    class: Gedmo\SoftDeleteable\Filter\SoftDeleteableFilter
                    enabled: true