doctrine:
    dbal:
      default_connection: default
      connections:
        default:
          driver:   %database_driver%
          host:     %database_host%
          port:     %database_port%
          dbname:   %database_name%
          user:     %database_user%
          password: %database_password%
          charset:  UTF8
          server_version: "5.6"
          mapping_types:
              enum: string
        tenant:
          driver:   %database_driver%
          host:     %database_host%
          port:     %database_port%
          platform_service: ~
          server_version: "5.6"
          dbname:   ~
          user:     ~
          password: ~
          charset:  UTF8
          wrapper_class: Dende\MultitenancyBundle\Connection\Wrapper
          mapping_types:
              enum: string
    orm:
        auto_generate_proxy_classes: %kernel.debug%
        default_entity_manager:   default

        resolve_target_entities:
            Dende\Calendar\Domain\Calendar\EventInterface: Gyman\Domain\Calendar\Event
            Dende\Calendar\Domain\Calendar\Event\OccurrenceInterface: Gyman\Domain\Calendar\Event\Occurrence

        entity_managers:
          default:
            auto_mapping:     false # disabled so we can assign entities to our own connections
            connection:       default
            dql:
                string_functions:
                    multi_concat: Spy\TimelineBundle\Driver\Doctrine\AST\Functions\MultiConcatFunction
                datetime_functions:
                    dayname: Gyman\Bundle\AppBundle\DQL\Dayname
            mappings:
                ClubBundle: ~
          tenant:
            auto_mapping:     false # disabled so we can assign entities to our own connections
            connection:       tenant
            mappings:
              DendeCalendarBundle:
                mapping:    true
                dir:        Resources/config/doctrine
                prefix:     Dende\Calendar\Domain
                alias:      Calendar
                is_bundle:  true
              GymanAppBundle:
                type:       yml
                mapping:    true
                dir:        Resources/config/doctrine
                prefix:     Gyman\Domain
                alias:      Gyman
                is_bundle:  true
            dql:
                string_functions:
                    multi_concat: Spy\TimelineBundle\Driver\Doctrine\AST\Functions\MultiConcatFunction
                datetime_functions:
                    dayname: Gyman\Bundle\AppBundle\DQL\Dayname
