doctrine:
    dbal:
      default_connection: default
      connections:
        default:
          driver:   %database_driver%
          host:     %database_host%
          port:     %database_port%
          dbname:   %database_name%
          user:     %database_user%
          password: %database_password%
          charset:  UTF8
          server_version: "5.6"
          mapping_types:
              enum: string
        club:
          driver:   %database_driver%
          host:     %database_host%
          port:     %database_port%
          platform_service: ~
          server_version: "5.6"
          dbname:   ~
          user:     ~
          password: ~
          charset:  UTF8
          wrapper_class: Gyman\Bundle\MultiDatabaseBundle\Connection\ConnectionWrapper
          mapping_types:
              enum: string
    orm:

        auto_generate_proxy_classes: %kernel.debug%
        default_entity_manager:   default

        entity_managers:
          default:
#            metadata_cache_driver: apc
#            result_cache_driver: apc
#            query_cache_driver: apc

            auto_mapping: false # disabled so we can assign entities to our own connections
            connection:       default
            dql:
                string_functions:
                    multi_concat: Spy\TimelineBundle\Driver\Doctrine\AST\Functions\MultiConcatFunction
                datetime_functions:
                    dayname: Gyman\Bundle\AppBundle\DQL\Dayname
            filters:
                softdeleteable:
                    class: Gedmo\SoftDeleteable\Filter\SoftDeleteableFilter
                    enabled: true
            mappings:
                StofDoctrineExtensionsBundle: ~
                UserBundle: ~
                ClubBundle: ~
#          view_model:
#            auto_mapping: false
#            connection: club
#            mappings:
#              ViewModel:
#                type: yml
#                prefix: Dende\Calendar\Domain
#                dir: %kernel.root_dir%/../vendor/dende/calendar-bundle/Resources/config/doctrine-viewmodel
#                is_bundle: false
#                alias: ViewModel
#          viewmodel_club:
#            auto_mapping: false
#            connection: club
#            mappings: ~
          club:
#            metadata_cache_driver: apc
#            result_cache_driver: apc
#            query_cache_driver: apc

            auto_mapping:     false # disabled so we can assign entities to our own connections
            connection:       club
            mappings:
              StofDoctrineExtensionsBundle: ~
              GymanAppBundle: ~
#              FiltersBundle: ~
#              ScheduleBundle: ~
#              SectionBundle: ~
#              TimelineBundle: ~
#              SpyTimelineBundle: ~
              Embedded:
                type: yml
                dir: "%kernel.root_dir%/../src/Gyman/Bundle/AppBundle/Resources/config/embedded"
                prefix: Gyman\Domain\Model
                alias: Model
                is_bundle: false
            dql:
                string_functions:
                    multi_concat: Spy\TimelineBundle\Driver\Doctrine\AST\Functions\MultiConcatFunction
                datetime_functions:
                    dayname: Gyman\Bundle\AppBundle\DQL\Dayname
            filters:
                softdeleteable:
                    class: Gedmo\SoftDeleteable\Filter\SoftDeleteableFilter
                    enabled: true