doctrine:
    dbal:
      default_connection: default
      connections:
        default:
          driver:   %database_driver%
          host:     %database_host%
          port:     %database_port%
          dbname:   %database_name%
          user:     %database_user%
          password: %database_password%
          charset:  UTF8
          server_version: "5.6"
          mapping_types:
              enum: string
        tenant:
          driver:   %database_driver%
          host:     %database_host%
          port:     %database_port%
          platform_service: ~
          server_version: "5.6"
          dbname:   ~
          user:     ~
          password: ~
          charset:  UTF8
          wrapper_class: Dende\MultidatabaseBundle\Connection\ConnectionWrapper
          mapping_types:
              enum: string
    orm:
        auto_generate_proxy_classes: %kernel.debug%
        default_entity_manager:   default

        entity_managers:
          default:
            auto_mapping: false # disabled so we can assign entities to our own connections
            connection:       default
            dql:
                string_functions:
                    multi_concat: Spy\TimelineBundle\Driver\Doctrine\AST\Functions\MultiConcatFunction
                datetime_functions:
                    dayname: Gyman\Bundle\AppBundle\DQL\Dayname
            filters:
                softdeleteable:
                    class: Gedmo\SoftDeleteable\Filter\SoftDeleteableFilter
                    enabled: true
            mappings:
                StofDoctrineExtensionsBundle: ~
                ClubBundle: ~
          tenant:
            auto_mapping:     false # disabled so we can assign entities to our own connections
            connection:       tenant
            mappings:
              StofDoctrineExtensionsBundle: ~
              DendeCalendarBundle:
                mapping:    true
                dir:        Resources/config/doctrine
                prefix:     Dende\Calendar\Domain
                alias:      Calendar
                is_bundle:  true
              GymanAppBundle:
                type:       yml
                mapping:    true
                dir:        Resources/config/doctrine
                prefix:     Gyman\Domain
                alias:      Gyman
                is_bundle:  true
            dql:
                string_functions:
                    multi_concat: Spy\TimelineBundle\Driver\Doctrine\AST\Functions\MultiConcatFunction
                datetime_functions:
                    dayname: Gyman\Bundle\AppBundle\DQL\Dayname
            filters:
                softdeleteable:
                    class: Gedmo\SoftDeleteable\Filter\SoftDeleteableFilter
                    enabled: true

doctrine_migrations:
    dir_name: "%kernel.root_dir%/DoctrineMigrations"
    namespace: Gyman\Migrations
    table_name: migration_versions
    name: Gyman Migrations