fos_user:
    db_driver:              orm
    firewall_name:          main
    user_class:             Gyman\Domain\User
    use_listener:           true
    use_username_form_type: true
    model_manager_name:     tenant
    from_email:
        address:        office@gyman.pl
        sender_name:    Gyman.pl
    profile:
        form:
            type:               Gyman\Bundle\AccountBundle\Form\Type\UserType
            name:               fos_user_profile_form
            validation_groups:  [Profile, Default]
    change_password:
        form:
            validation_groups:  [ChangePassword, Default]
    registration:
        confirmation:
#            from_email: # Use this node only if you don't want the global email address for the confirmation email
#                address:        ...
#                sender_name:    ...
            enabled:    false
            template:   MailerBundle:Templates:registerConfirmation.html.twig
        form:
            type:               Gyman\Bundle\AccountBundle\Form\Type\RegisterType
            name:               dende_registration_form
            validation_groups:  [Registration, Default]
    resetting:
        token_ttl: 86400
        email:
            template:   MailerBundle:Templates:resetting.html.twig
        form:
            validation_groups:  [ResetPassword, Default]
    service:
        mailer:                 fos_user.mailer.twig_swift
        email_canonicalizer:    fos_user.util.canonicalizer.default
        username_canonicalizer: fos_user.util.canonicalizer.default
        token_generator:        fos_user.util.token_generator.default
        user_manager:           gyman.users.user_manager
    group:
        group_class: Gyman\Bundle\ClubBundle\Entity\Group
#    group:
#        group_class:    ~ # Required when using groups
#        group_manager:  fos_user.group_manager.default
#        form:
#            type:               fos_user_group
#            name:               fos_user_group_form
#            validation_groups:  [Registration, Default]