layout:
    resource: "@LayoutBundle/Controller/"
    type:     annotation
    prefix:   /

default:
    resource: "@DefaultBundle/Controller/"
    type:     annotation
    prefix:   /

members:
    resource: "@MembersBundle/Controller/"
    type:     annotation
    prefix:   /member

vouchers:
    resource: "@VouchersBundle/Controller/"
    type:     annotation
    prefix:   /voucher

oneup_uploader:
    resource: .
    type: uploader