gyman_settings:
    resource: "@GymanSettingsBundle/Controller/"
    type:     annotation
    prefix:   /

gyman_landing_page:
    resource: "@GymanLandingPageBundle/Controller/"
    type:     annotation
    prefix:   /
    host:     %base_url%

gyman_app:
    resource: "@GymanAppBundle/Controller/"
    type:     annotation
    prefix:   /

gyman_reports:
    resource: "@GymanReportsBundle/Controller/"
    type:     annotation
    prefix:   /reports

account:
    resource: "@AccountBundle/Controller/"
    type:     annotation
    prefix:   /

dashboard:
    resource: "@DashboardBundle/Controller/"
    type:     annotation
    prefix:   /dashboard

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

fos_user_group:
    resource: "@FOSUserBundle/Resources/config/routing/group.xml"
    prefix: /group

#@todo: fix
#dende_calendar_rest:
#  type: rest
#  resource: "@DendeCalendarBundle/Controller/RestController.php"
#  prefix: api/calendar
#  defaults:
#    _format: json

dende_calendar:
  type: annotation
  resource: "@DendeCalendarBundle/Controller/DefaultController.php"
  prefix: calendar
