gyman_old_rio:
    resource: "@GymanOldRioBundle/Resources/config/routing.yml"
    prefix:   /

#admin_area:
#    resource: "@SonataAdminBundle/Resources/config/routing/sonata_admin.xml"
#    prefix: /admin
#
#_sonata_admin:
#    resource: .
#    type: sonata_admin
#    prefix: /admin

gyman_app:
    resource: "@GymanAppBundle/Controller/"
    type:     annotation
    prefix:   /

gyman_reports:
    resource: "@GymanReportsBundle/Controller/"
    type:     annotation
    prefix:   /reports

#timeline:
#    resource: "@TimelineBundle/Controller/"
#    type:     annotation
#    prefix:   /timeline

account:
    resource: "@AccountBundle/Controller/"
    type:     annotation
    prefix:   /

dashboard:
    resource: "@DashboardBundle/Controller/"
    type:     annotation
    prefix:   /dashboard

clubs:
    resource: "@ClubBundle/Controller/"
    type:     annotation
    prefix:   /clubs

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

fos_user_group:
    resource: "@FOSUserBundle/Resources/config/routing/group.xml"
    prefix: /group

dende_calendar_rest:
  type: rest
  resource: @DendeCalendarBundle/Controller/RestController.php
  prefix: api/calendar
  defaults:
    _format: json

dende_calendar:
  type: annotation
  resource: @DendeCalendarBundle/Controller/DefaultController.php
  prefix: calendar