easy_admin_bundle:
    resource: "@AdminBundle/Controller/"
    type:     annotation
    host:     admin.{base_url}
    defaults:
      base_url: '%base_url%'
    requirements:
      base_url: '%base_url%'
    prefix:   /

gyman_settings:
    resource: "@GymanSettingsBundle/Controller/"
    type:     annotation
    prefix:   /settings

gyman_landing_page:
    resource: "@GymanLandingPageBundle/Controller/"
    type:     annotation
    prefix:   /
    host:     %base_url%

gyman_app:
    resource: "@GymanAppBundle/Controller/"
    type:     annotation
    prefix:   /
    host:     "{_subdomain}.{_base_url}"
    defaults:
      _subdomain:  dummy-localhost
      _base_url:   '%base_url%'
    requirements:
      _subdomain:  '[a-z0-9\-]{3,}'
      _base_url:   '%base_url%'

gyman_reports:
    resource: "@GymanReportsBundle/Controller/"
    type:     annotation
    prefix:   /reports

dashboard:
    resource: "@DashboardBundle/Controller/"
    type:     annotation
    prefix:   /dashboard

subdomain_fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
    defaults:
      _subdomain:  dummy-localhost
      _base_url:   '%base_url%'
    requirements:
      _subdomain:  '[a-z0-9\-]{3,}'
      _base_url:   '%base_url%'

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

fos_user_group:
    resource: "@FOSUserBundle/Resources/config/routing/group.xml"
    prefix: /group

#@todo: fix
#dende_calendar_rest:
#  type: rest
#  resource: "@DendeCalendarBundle/Controller/RestController.php"
#  prefix: api/calendar
#  defaults:
#    _format: json

subdomain_dende_calendar:
    type: annotation
    resource: "@DendeCalendarBundle/Controller/DefaultController.php"
    prefix: calendar
    host:     "{_subdomain}.{_base_url}"
    defaults:
      _subdomain:  dummy-localhost
      _base_url:   '%base_url%'
    requirements:
      _subdomain:  '[a-z0-9\-]{3,}'
      _base_url:   '%base_url%'