gyman_app:
    resource: "@GymanAppBundle/Controller/"
    type:     annotation
    prefix:   /

gyman_multi_database:
    resource: "@GymanMultiDatabaseBundle/Controller/"
    type:     annotation
    prefix:   /

#timeline:
#    resource: "@TimelineBundle/Controller/"
#    type:     annotation
#    prefix:   /timeline

account:
    resource: "@AccountBundle/Controller/"
    type:     annotation
    prefix:   /

reports:
    resource: "@ReportsBundle/Controller/"
    type:     annotation
    prefix:   /report

lists:
    resource: "@ListsBundle/Controller/"
    type:     annotation
    prefix:   /list

filters:
    resource: "@FiltersBundle/Controller/"
    type:     annotation
    prefix:   /filter

dashboard:
    resource: "@DashboardBundle/Controller/"
    type:     annotation
    prefix:   /

entries:
    resource: "@EntriesBundle/Controller/"
    type:     annotation
    prefix:   /entries

schedule:
    resource: "@ScheduleBundle/Controller/"
    type:     annotation
    prefix:   /schedule

clubs:
    resource: "@ClubBundle/Controller/"
    type:     annotation
    prefix:   /clubs

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

fos_user_group:
    resource: "@FOSUserBundle/Resources/config/routing/group.xml"
    prefix: /group
