entries:
    resource: "@EntriesBundle/Controller/"
    type:     annotation
    prefix:   /entries

schedule:
    resource: "@ScheduleBundle/Controller/"
    type:     annotation
    prefix:   /schedule

layout:
    resource: "@LayoutBundle/Controller/"
    type:     annotation
    prefix:   /layout

default:
    resource: "@DefaultBundle/Controller/"
    type:     annotation
    prefix:   /

members:
    resource: "@MembersBundle/Controller/"
    type:     annotation
    prefix:   /members

vouchers:
    resource: "@VouchersBundle/Controller/"
    type:     annotation
    prefix:   /vouchers

oneup_uploader:
    resource: .
    type: uploader