security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        LOCK_THIS:      ~ # todo: remove

        ROLE_MEMBER:      ~

        ROLE_USER:        ~
        ROLE_OWNER:       ROLE_USER
        ROLE_MANAGER:     ROLE_OWNER
        ROLE_ADMIN:       ROLE_MANAGER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
           pattern: ^/
           form_login:
               provider: fos_userbundle
               csrf_provider: security.csrf.token_manager
           logout:
               path:   /logout
#               handlers: [gyman.account.logout_handler]
           anonymous:    true

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }

#        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY } todo: use admin
        - { path: ^/register, role: ROLE_SUPER_ADMIN }
#        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY } todo: use admin
        - { path: ^/resetting, role: ROLE_SUPER_ADMIN }

        - { path: ^/, role: ROLE_USER }
#        - { path: ^/admin/, role: ROLE_ADMIN } todo: use admin
        - { path: ^/admin/, role: ROLE_SUPER_ADMIN }

        - { path: ^/schedule/, role: LOCK_THIS } # todo: remove
