security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_USER:        ~

        ROLE_MEMBER:      ROLE_USER

        ROLE_INSTRUCTOR:  ROLE_USER

        ROLE_MODERATOR:   ROLE_MODERATOR
        ROLE_ADMIN:       ROLE_STAFF
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
           pattern: ^/
           form_login:
               provider: fos_userbundle
               csrf_provider: security.csrf.token_manager
           logout:
               path:   /logout
           anonymous:    true

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/calendar/events, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/calendar/, role: ROLE_MODERATOR }
        - { path: ^/register, role: ROLE_SUPER_ADMIN }
        - { path: ^/resetting, role: ROLE_SUPER_ADMIN }
        - { path: ^/dashboard/member, role: ROLE_MEMBER }
        - { path: ^/dashboard, role: ROLE_USER }
        - { path: ^/profile, roles: IS_AUTHENTICATED_REMEMBERED }
        - { path: ^/admin, role: ROLE_SUPER_ADMIN }
        - { path: ^/settings, role: ROLE_ADMIN }
        - { path: ^/, role: IS_AUTHENTICATED_ANONYMOUSLY }
