security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512
        Gyman\Bundle\AppBundle\Security\MemberUser: sha512

    role_hierarchy:
        ROLE_MEMBER:      ~

        ROLE_INSTRUCTOR:  ~

        ROLE_USER:        ~
        ROLE_OWNER:       ROLE_USER
        ROLE_MANAGER:     ROLE_OWNER
        ROLE_ADMIN:       ROLE_MANAGER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        chain_provider:
            chain:
                providers: [members, fos_userbundle]
        fos_userbundle:
            id: fos_user.user_provider.username
        members:
            id: gyman.app.member_user_provider

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
           pattern: ^/
           form_login:
               provider: chain_provider
               csrf_provider: security.csrf.token_manager
           logout:
               path:   /logout
           anonymous:    true

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/calendar/events, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/calendar/, role: ROLE_USER }
        - { path: ^/register, role: ROLE_SUPER_ADMIN }
        - { path: ^/resetting, role: ROLE_SUPER_ADMIN }
        - { path: ^/dashboard/member, role: ROLE_MEMBER }
        - { path: ^/dashboard, role: IS_AUTHENTICATED_REMEMBERED }
        - { path: ^/profile, role: IS_AUTHENTICATED_REMEMBERED }
        - { path: ^/admin, role: ROLE_SUPER_ADMIN }
        - { path: ^/settings, role: ROLE_ADMIN }
        - { path: ^/, role: IS_AUTHENTICATED_ANONYMOUSLY }
