sonata_core:
    form_type: horizontal

sonata_block:
    default_contexts: [cms]
    blocks:
        sonata.block.service.text: ~
        sonata.block.service.rss: ~
        sonata.admin.block.admin_list:
            contexts: [admin]

sonata_admin:
    title:                Rosomak Admin
    title_logo:           bundles/app/img/bg.png