spy_timeline:
    drivers: # define only one.
        orm:
            object_manager: doctrine.orm.club_entity_manager
            classes:
                timeline:         'Gyman\Bundle\TimelineBundle\Entity\Timeline'
                action:           'Gyman\Bundle\TimelineBundle\Entity\Action'
                component:        'Gyman\Bundle\TimelineBundle\Entity\Component'
                action_component: 'Gyman\Bundle\TimelineBundle\Entity\ActionComponent'

    notifiers:
        - spy_timeline.unread_notifications

    query_builder:
        classes:
            factory:   Spy\Timeline\Driver\QueryBuilder\QueryBuilderFactory
            asserter:  Spy\Timeline\Driver\QueryBuilder\Criteria\Asserter
            operator:  Spy\Timeline\Driver\QueryBuilder\Criteria\Operator

    filters:
        duplicate_key:
            priority:             10
        data_hydrator:
            priority:             20
            filter_unresolved:    false
            locators:
                - spy_timeline.filter.data_hydrator.locator.doctrine_orm
    spread:
        on_subject: true          # Spread each action on subject too
        on_global_context: true   # Spread automatically on global context
        deployer: spy_timeline.spread.deployer.default
        delivery: immediate

    render:
        path:     'TimelineBundle:Timeline'
        resources:
          - TimelineBundle:Timeline:components.html.twig