<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'gyman.app.remove_entry_from_occurrence' shared service.

return $this->services['gyman.app.remove_entry_from_occurrence'] = new \Gyman\Bundle\AppBundle\Services\RemoveEntryFromOccurrence(${($_ = isset($this->services['gyman.entries.repository']) ? $this->services['gyman.entries.repository'] : $this->load(__DIR__.'/getGyman_Entries_RepositoryService.php')) && false ?: '_'});
