<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'gyman.default.menu.main' shared service.

return $this->services['gyman.default.menu.main'] = ${($_ = isset($this->services['gyman.default.menu_builder']) ? $this->services['gyman.default.menu_builder'] : $this->load(__DIR__.'/getGyman_Default_MenuBuilderService.php')) && false ?: '_'}->main();
