<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'gyman.members.upload_member_foto_handler' shared service.

return $this->services['gyman.members.upload_member_foto_handler'] = new \Gyman\Application\Handler\UploadMemberFotoHandler('/vagrant/app/../web/uploads/gallery/', $this->get($this->getParameter("subdomain_provider_service")));
