<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'gyman.entries.only_enter_once.validator' shared service.

return $this->services['gyman.entries.only_enter_once.validator'] = new \Gyman\Bundle\AppBundle\Validator\OnlyEnterOnceValidator();
