<?php

namespace Dende\ScheduleBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query\Expr\Join;

/**
 * ActivityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActivityRepository extends EntityRepository {

    public function getActivitiesQuery() {
        return $this->createQueryBuilder("a")
                        ->select();
    }

    public function getPopularityQuery() {
        return $this->createQueryBuilder("a")
                        ->select("a.name", "count(en.id) as cnt")
                        ->join("a.events", "e")
                        ->join("e.occurences", "o")
                        ->join("o.entries", "en")
                        ->setMaxResults(6)
                        ->groupBy("a.name")
                        ->orderBy("cnt", "DESC");
    }

    public function getPopularity() {
        $query = $this->getPopularityQuery();
        return $query->getQuery()->execute();
    }

    public function getAllActivities() {
        return $this->getActivitiesQuery()->getQuery()->execute();
    }

    public function getTodayActivities($today = null) { {
            if (!$today)
            {
                $today = strtolower(date('l'));
            }

            return $this->getActivitiesQuery()
                            ->join("a.events", "e")
                            ->where("e.dayOfWeek = :day")
                            ->setParameter("day", $today)
                            ->getQuery()->execute();
        }
    }

}
