<?php

namespace Dende\ScheduleBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query;

/**
 * EventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventRepository extends EntityRepository {

    /**
     * 
     * @param int $timeOffsetInMinutes
     * @return DoctrineCollection
     */
    public function getCurrentEvents($timeOffsetInMinutes = null) {
        $dayOfWeek = strtolower(date('l'));

        if ($timeOffsetInMinutes)
        {
            $hour = date('H:i', strtotime(sprintf("+%d minutes", $timeOffsetInMinutes)));
        }
        else
        {
            $hour = date('H:i');
        }

        $queryBuilder = $this->createQueryBuilder("e")
                ->where("e.dayOfWeek = :day")
                ->andWhere("e.startHour <= :hour")
                ->andWhere("e.endHour >= :hour")
                ->setParameters(array(
            "day"  => $dayOfWeek,
            "hour" => $hour
        ));

        $query = $queryBuilder->getQuery();

        return $query->execute();
    }

    public function getAllEvents() {
        $queryBuilder = $this->createQueryBuilder("e");

        $query = $queryBuilder->getQuery();

        return $query->execute();
    }

    /**
     * 
     * @param integer $weekNumber
     * @return type
     */
    public function getAllEventsForWeek($year,$weekNumber) {
        
        $weekStart = new \DateTime(sprintf("%d-W%d-1",$year,$weekNumber));
        $weekEnd = new \DateTime(sprintf("%d-W%d-0",$year,$weekNumber+1));
        
        $queryBuilder = $this->createQueryBuilder("e");
        $queryBuilder->where("e.startDate >= :weekStart");
        $queryBuilder->andWhere("e.endDate <= :weekEnd or e.endDate is null");
        $queryBuilder->setParameters([
            "weekStart" => $weekStart,
            "weekEnd" => $weekEnd
        ]);
        $query = $queryBuilder->getQuery();

        return $query->execute();
    }

    public function getTodayEvents() {
        $now = new \DateTime();
        $query = $this->getEventsForDateQuery($now);

        return $query->execute();
    }

    public function getEventsForDateArray(\DateTime $date) {
        $query = $this->getEventsForDateQuery($date);
        return $query->execute([]);
    }

    public function getEventsForDate(\DateTime $date) {
        $queryBuilder = $this->createQueryBuilder("e");
        $queryBuilder
                ->join("e.activity", "a")
                ->where("e.dayOfWeek = :day")
                ->setParameter("day", strtolower($date->format("l")));
        $query = $queryBuilder->getQuery();

        return $query->execute();
    }

    /**
     * 
     * @param \DateTime $date
     * @return QueryBuilder
     */
    private function getEventsForDateQuery(\DateTime $date) {
        $queryBuilder = $this->createQueryBuilder("e");
        $queryBuilder
                ->select("e.id, e.startHour, e.endHour, a.name")
                ->join("e.activity", "a")
                ->where("e.dayOfWeek = :day")
                ->setParameter("day", strtolower($date->format("l")));
        $query = $queryBuilder->getQuery();

        return $query;
    }

}
