<?php

namespace Dende\ScheduleBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query;
use Dende\ScheduleBundle\Entity\Event;

/**
 * EventMetaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OccurenceRepository extends EntityRepository {

    public function insertWeeklyOccurencesForEvent(Event $event) {
        var_dump($event->getId());
    }

    public function getOccurencesForPeriod(\DateTime $startDate, \DateTime $endDate) {
        $queryBuilder = $this->createQueryBuilder("o");
        $queryBuilder
            ->where("o.startDate BETWEEN :start AND :end")
            ->setParameters([
                "start" => $startDate->modify("00:00:00"),
                "end"   => $endDate->modify("23:59:59"),
        ]);

        return $queryBuilder->getQuery()->execute();
    }

}
