<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container6bxxyxu\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container6bxxyxu/appProdProjectContainer.php') {
    touch(__DIR__.'/Container6bxxyxu.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\Container6bxxyxu\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \Container6bxxyxu\appProdProjectContainer();
