<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'account_bundle.updated_profile_subscriber' shared service.

$this->services['account_bundle.updated_profile_subscriber'] = $instance = new \Gyman\Bundle\AccountBundle\Service\Subscriber\UpdatedProfileSubscriber();

$instance->setRouter(${($_ = isset($this->services['router']) ? $this->services['router'] : $this->getRouterService()) && false ?: '_'});
$instance->setSession(${($_ = isset($this->services['session']) ? $this->services['session'] : $this->load(__DIR__.'/getSessionService.php')) && false ?: '_'});

return $instance;
