<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'gyman.dashboard.members_query' shared service.

return $this->services['gyman.dashboard.members_query'] = new \Gyman\Bundle\DashboardBundle\Service\MembersCalendarQuery();
