<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'gyman.club.factory' shared service.

return $this->services['gyman.club.factory'] = new \Gyman\Bundle\ClubBundle\Factory\ClubFactory();
