<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'dende_calendar.factory.occurrence' shared service.

return $this->services['dende_calendar.factory.occurrence'] = new \Dende\Calendar\Application\Factory\OccurrenceFactory(${($_ = isset($this->services['dende_calendar.id_generator']) ? $this->services['dende_calendar.id_generator'] : $this->load(__DIR__.'/getDendeCalendar_IdGeneratorService.php')) && false ?: '_'});
