<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'gyman.app.validator.voucher_amount_for_credit_entries_constraint' shared service.

return $this->services['gyman.app.validator.voucher_amount_for_credit_entries_constraint'] = new \Gyman\Bundle\AppBundle\Validator\MaximumAmountGreaterThanCreditEntriesValidator();
