services:
  gyman.multidatabase.database_switcher:
    class: Gyman\Bundle\MultiDatabaseBundle\Listener\DatabaseSwitcher
    scope: request
    arguments:
      - @=service(parameter('subdomain_provider_service'))
      - @doctrine.orm.entity_manager
      - @doctrine.dbal.club_connection
    tags:
        - { name: kernel.event_listener, method: onKernelRequest, event: kernel.request, priority: 255 }

  gyman.multidatabase.credentials_storage:
    class: Gyman\Bundle\MultiDatabaseBundle\Services\CredentialsStorage

  gyman.multidatabase.collector.db_connections:
    class: Gyman\Bundle\MultiDatabaseBundle\DataCollector\DatabaseConnectionsDataCollector
    arguments: [@doctrine.dbal.default_connection, @doctrine.dbal.club_connection]
    tags:
      - { name: data_collector, template: "GymanMultiDatabaseBundle:Toolbar:DatabaseConnections.html.twig", id: "database_connections" }

  gyman.multidatabase.slugify:
    class: Gyman\Bundle\MultiDatabaseBundle\Services\Slugify

  gyman.multidatabase.database_worker:
    class: Gyman\Bundle\MultiDatabaseBundle\Services\DatabaseWorker
    arguments:
      - "%club_database_name_template%"
      - "%database_user%"
      - "%database_password%"
    calls:
      - [setSlugifier, [@gyman.multidatabase.slugify]]
      - [setDefaultConnection, [@doctrine.dbal.default_connection]]
      - [setClubConnection, [@doctrine.dbal.club_connection]]
      - [setDefaultEntityManager, [@doctrine.orm.default_entity_manager]]
      - [setClubEntityManager, [@doctrine.orm.club_entity_manager]]

  gyman.multidatabase.club_connection_command_listener:
      class: Gyman\Bundle\MultiDatabaseBundle\Listener\ClubConnectionCommandListener
      calls:
        - [setClubRepository, [@gyman.club.repository]]
        - [setConnectionWrapper, [@doctrine.dbal.club_connection]]
        - [setSchemaManager, ["@=service('doctrine.dbal.default_connection').getSchemaManager()"]]
      tags:
        - { name: kernel.event_listener, event: console.command, method: onConsoleCommand, priority: 255 }

  gyman.multidatabase.doctrine_fixtures_load_listener:
      class: Gyman\Bundle\MultiDatabaseBundle\Listener\DoctrineFixturesLoadListener
#      calls:
#        - [setOptions, [{default: %standardFixtures%, club: %clubFixtures% }]]
      tags:
        - { name: kernel.event_listener, event: console.command, method: onConsoleCommand }

  gyman.multidatabase.command:
    abstract: true
    class: Gyman\Bundle\MultiDatabaseBundle\Command\AbstractCommand
    calls:
      - [setDatabaseWorker, [@gyman.multidatabase.database_worker]]

  gyman.multidatabase.command.create_database:
    class: Gyman\Bundle\MultiDatabaseBundle\Command\CreateClubDatabaseCommand
    tags:
      - { name: console.command }

  gyman.multidatabase.command.assign_user_to_club:
    class: Gyman\Bundle\MultiDatabaseBundle\Command\AssignUserToClubCommand
    tags:
      - { name: console.command }

  gyman.multidatabase.command.drop_database:
    class: Gyman\Bundle\MultiDatabaseBundle\Command\DropClubDatabaseCommand
    parent: gyman.multidatabase.command
    tags:
      - { name: console.command }

  gyman.multidatabase.command.migrations.migrate:
    class: Gyman\Bundle\MultiDatabaseBundle\Command\MigrationsMigrateCommand
    parent: gyman.multidatabase.command
    tags:
      - { name: console.command }

  gyman.multidatabase.command.migrations.generate:
    class: Gyman\Bundle\MultiDatabaseBundle\Command\MigrationsGenerateCommand
    parent: gyman.multidatabase.command
    tags:
      - { name: console.command }

  gyman.multidatabase.form.club_switch:
    class: Gyman\Bundle\MultiDatabaseBundle\Form\ClubSwitchType
    arguments: [@security.context]
    tags:
      - { name: form.type, alias: gyman_default_clubswitch }

