parameters:
    member_entity.class: Gyman\Bundle\MembersBundle\Entity\Member
    member_repository.class: Gyman\Bundle\MembersBundle\Entity\MemberRepository

services:

#@todo: rename to commas
    gyman_members_manager:
      parent: gyman_base_entity_manager
      class:  Gyman\Bundle\MembersBundle\EntityManager\MemberManager
      calls:
        - [setClass, [%member_entity.class%]]

    gyman_members_member_form_type:
      class: Gyman\Bundle\MembersBundle\Form\MemberType
      arguments:
        - @oneup_uploader.templating.uploader_helper
      tags:
        - { name: form.type, alias: gyman_members_member_form_type }

    gyman.members.menu_builder:
        class: Gyman\Bundle\MembersBundle\Menu\Builder
        arguments: [@knp_menu.factory, @security.context]

    gyman.members.menu.tabs:
        class:            Knp\Menu\MenuItem
        factory_service:  gyman.members.menu_builder
        factory_method:   tabs
        scope:            request
        arguments:        [@request]
        tags:
            - { name: knp_menu.menu, alias: gyman.members.menu.tabs }

    gyman.members.menu.tabs_picture:
        class:            Knp\Menu\MenuItem
        factory_service:  gyman.members.menu_builder
        factory_method:   picture
        scope:            request
        tags:
            - { name: knp_menu.menu, alias: gyman.members.menu.tabs_picture }

    # @todo: remove
    member_repository:
        class:          "%member_repository.class%"
        factory_service: doctrine
        factory_method:  getRepository
        arguments: [ "%member_entity.class%" ]

    # @todo: rename
    dende.upload_listener:
        class: Gyman\Bundle\MembersBundle\Services\Listener\UploadListener
        arguments: [@doctrine]
        tags:
            - { name: kernel.event_listener, event : oneup_uploader.post_persist, method: onUpload}

    dende.image_rescale_listener:
        class: Gyman\Bundle\MembersBundle\Services\Listener\ImageRescaleListener
        arguments: [@doctrine]
        tags:
            - { name: kernel.event_listener, event : oneup_uploader.post_persist, method: onUpload}
