<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'gyman.app.globals_factory' shared service.

$this->services['gyman.app.globals_factory'] = $instance = new \Gyman\Bundle\AppBundle\GlobalsFactory(${($_ = isset($this->services['gyman.app.subdomain_provider']) ? $this->services['gyman.app.subdomain_provider'] : $this->load(__DIR__.'/getGyman_App_SubdomainProviderService.php')) && false ?: '_'});

$instance->setUp();

return $instance;
