<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'account_bundle.profile.edit_type' shared service.

return $this->services['account_bundle.profile.edit_type'] = new \Gyman\Bundle\AccountBundle\Form\Type\UserType();
