<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'dende_calendar.form_type.range_dates' shared service.

return $this->services['dende_calendar.form_type.range_dates'] = new \Dende\CalendarBundle\Form\Type\UpdateEventType\RangeDatesType();
