<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'gyman.entries.cant_enter_past_occurrence.validator' shared service.

return $this->services['gyman.entries.cant_enter_past_occurrence.validator'] = new \Gyman\Bundle\AppBundle\Validator\CantEnterPastOccurrenceValidator();
