<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'gyman.app.command.dump_hosts' shared service.

return $this->services['gyman.app.command.dump_hosts'] = new \Gyman\Bundle\AppBundle\Command\DumpHostsCommand();
