<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'knp_menu.menu_provider.lazy' shared service.

return $this->services['knp_menu.menu_provider.lazy'] = new \Knp\Menu\Provider\LazyProvider(array('actions' => function () {
    return ${($_ = isset($this->services['gyman.dashboard.menu.main']) ? $this->services['gyman.dashboard.menu.main'] : $this->load(__DIR__.'/getGyman_Dashboard_Menu_MainService.php')) && false ?: '_'};
}, 'main' => function () {
    return ${($_ = isset($this->services['gyman.settings.menu.main']) ? $this->services['gyman.settings.menu.main'] : $this->load(__DIR__.'/getGyman_Settings_Menu_MainService.php')) && false ?: '_'};
}, 'profile' => function () {
    return ${($_ = isset($this->services['gyman.default.menu.profile']) ? $this->services['gyman.default.menu.profile'] : $this->load(__DIR__.'/getGyman_Default_Menu_ProfileService.php')) && false ?: '_'};
}, 'gyman.members.menu.tabs' => function () {
    return ${($_ = isset($this->services['gyman.members.menu.tabs']) ? $this->services['gyman.members.menu.tabs'] : $this->load(__DIR__.'/getGyman_Members_Menu_TabsService.php')) && false ?: '_'};
}, 'gyman.landing.menu.tabs' => function () {
    return ${($_ = isset($this->services['gyman.landing.menu.tabs']) ? $this->services['gyman.landing.menu.tabs'] : $this->load(__DIR__.'/getGyman_Landing_Menu_TabsService.php')) && false ?: '_'};
}, 'gyman.members.menu.tabs_picture' => function () {
    return ${($_ = isset($this->services['gyman.members.menu.tabs_picture']) ? $this->services['gyman.members.menu.tabs_picture'] : $this->load(__DIR__.'/getGyman_Members_Menu_TabsPictureService.php')) && false ?: '_'};
}));
