Gyman\Calendar\Domain\Calendar:
  type: entity
  inheritanceType: SINGLE_TABLE
  discriminatorColumn:
    name: discriminator
    type: string
  discriminatorMap:
    bundle: Gyman\Calendar\Domain\Calendar
#    gyman:  Gyman\Domain\Calendar

  table: calendars
  repositoryClass: Gyman\Bundle\CalendarBundle\Repository\ORM\CalendarRepository

  id:
    id:
      type: uuid
      generator:
        strategy: CUSTOM
      customIdGenerator:
        class: Ramsey\Uuid\Doctrine\UuidGenerator

  fields:
    title:
      type: string
      nullable: false
      length: 255

    deletedAt:
      type: datetime
      nullable: true

  oneToMany:
    events:
      targetEntity: Gyman\Calendar\Domain\Calendar\EventInterface
      mappedBy: calendar
      cascade: [all]
