Gyman\Calendar\Domain\Calendar\Event\EventData:
  type: embeddable

  embedded:
    repetitions:
      class: Gyman\Calendar\Domain\Calendar\Event\Repetitions

  fields:
    startDate:
      type: datetime
      nullable: false

    endDate:
      type: datetime
      nullable: false

    title:
      type: string
      nullable: false
      length: 255
