<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'gyman.settings.sections_handler' shared service.

return $this->services['gyman.settings.sections_handler'] = new \Gyman\Application\Handler\UpdateSectionsHandler(${($_ = isset($this->services['gyman.repository.section']) ? $this->services['gyman.repository.section'] : $this->load(__DIR__.'/getGyman_Repository_SectionService.php')) && false ?: '_'});
