---
Gyman\Application\Command\CreateClubCommand:
  properties:
    username:
      - NotNull: ~
      - Length: {min: 100}
    email:
      - NotNull: ~
      - Email: ~
    password:
      - NotNull: ~
    club:
      - NotNull: {groups: ['create_club_form']}
    subdomain:
      - NotNull: ~
