Gyman\Application\Command\UpdateSettingsCommand:
  properties:
    details:
      - Valid: ~
    sections:
      - Valid: ~
      - Count:
          min: 1
          minMessage: Musi istnieć przynajmniej 1 sekcja!
          max: 10
          maxMessage: Nie może istnieć więcej niż 10 sekcji!
    name:
      - NotBlank:
          message: Pole nie może być puste!
      - Length:
          min: 1
          max: 50
    uploadLogo:
      - File:
          maxSize: 2M
      - Image:
          mimeTypes:
            - image/png
            - image/jpg
            - image/jpeg
            - image/gif