Gyman\Bundle\AppBundle\Entity\Entry:
  type:   entity
  table:  entries
  repositoryClass:  Gyman\Bundle\AppBundle\Entity\EntryRepository
  embedded:
    price:
      class: Gyman\Domain\Model\Price
      columnPrefix: false

  manyToOne:
    member:
      targetEntity: Gyman\Bundle\AppBundle\Entity\Member
      inversedBy: entries
    voucher:
      targetEntity: Gyman\Bundle\AppBundle\Entity\Voucher
      inversedBy: entries

  id:
    id:
      type: integer
      generator: { strategy: AUTO }

  gedmo:
    soft_deleteable:
      field_name: deletedAt
      time_aware: false

  fields:
    startDate:
      type: datetime
      nullable: true #false

    endDate:
      type: datetime
      nullable: true #false

    type:
      type: string
      nullable: false

    deletedAt:
      name: deleted_at
      type: datetime
      nullable: true #false

    createdAt:
      name: created_at
      type: datetime
      nullable: true
      gedmo:
        timestampable:
          on: create

    updatedAt:
      name: updated_at
      type: datetime
      nullable: true
      gedmo:
        timestampable:
          on: update
