Gyman\Domain\Entry:
  type:   entity
  table:  entries
  repositoryClass:  Gyman\Bundle\AppBundle\Repository\EntryRepository
  embedded:
    price:
      class: Gyman\Domain\Entry\Price
      columnPrefix: price_

  manyToOne:
    member:
      targetEntity: Gyman\Domain\Member
      inversedBy: entries
      cascade: ["persist"]

    voucher:
      targetEntity: Gyman\Domain\Voucher
      inversedBy: entries
      cascade: ["persist"]

    occurrence:
      targetEntity: Dende\Calendar\Domain\Calendar\Event\Occurrence
      inversedBy: occurrence
      nullable: true
      orphanRemoval: false
      cascade: ["persist"]
      joinColumns:
        occurrence_id:
          referencedColumnName: id
          unique: false
          onDelete: SET NULL
          onUpdate: RESTRICT

  id:
    id:
      type: guid
      generator: { strategy: UUID }

  gedmo:
    soft_deleteable:
      field_name: deletedAt
      time_aware: false

  fields:
    startDate:
      type: datetime
      nullable: false

    endDate:
      type: datetime
      nullable: true #false

    type:
      type: string
      nullable: false

    deletedAt:
      name: deleted_at
      type: datetime
      nullable: true

    createdAt:
      name: created_at
      type: datetime
      nullable: false
      gedmo:
        timestampable:
          on: create

    updatedAt:
      name: updated_at
      type: datetime
      nullable: false
      gedmo:
        timestampable:
          on: update
