Gyman\Domain\Member:
  type:   entity
  table:  members
  repositoryClass:  Gyman\Bundle\AppBundle\Repository\MemberRepository

  indexes:
    index_members_barcode:
      columns:
        - barcode
    index_members_name:
      columns:
        - lastname
        - firstname

  embedded:
    email:
      class: Gyman\Domain\Member\EmailAddress
      columnPrefix: false
    details:
      class: Gyman\Domain\Member\Details
      columnPrefix: false

  id:
    id:
      type: uuid
      generator:
        strategy: CUSTOM
      customIdGenerator:
        class: Ramsey\Uuid\Doctrine\UuidGenerator

  gedmo:
    soft_deleteable:
      field_name: deletedAt
      time_aware: false

  manyToMany:
    sections:
      targetEntity: Gyman\Domain\Section
      inversedBy: members

  oneToMany:
    vouchers:
      targetEntity: Gyman\Domain\Voucher
      mappedBy: member
      cascade: ["all"]

    entries:
      targetEntity: Gyman\Domain\Entry
      mappedBy: member
      cascade: ["all"]

  oneToOne:
    currentVoucher:
      targetEntity: Gyman\Domain\Voucher
      cascade: ["all"]
      inversedBy: member
      joinColumn:
        name: current_voucher_id
        referencedColumnName: id
        onDelete: SET NULL
        nullable: true

    lastEntry:
      targetEntity: Gyman\Domain\Entry
      cascade: ["persist"]
      joinColumn:
        name: last_entry_id
        referencedColumnName: id
        onDelete: SET NULL
        nullable: true

  fields:
    nameSlug:
      name: name_slug
      type: string
      nullable: true
      gedmo:
        slug:
          fields: [ details.firstname, details.lastname]
          updatable: true
          separator: -
          unique: true

    deletedAt:
      name: deleted_at
      type: datetime
      nullable: true

    createdAt:
      name: created_at
      type: datetime
      nullable: true
      gedmo:
        timestampable:
          on: create

    updatedAt:
      name: updated_at
      type: datetime
      nullable: true
      gedmo:
        timestampable:
          on: update
