Gyman\Bundle\AppBundle\Entity\Member:
  type:   entity
  table:  members
  repositoryClass:  Gyman\Bundle\AppBundle\Entity\MemberRepository
  embedded:
    email:
      class: Gyman\Domain\Model\EmailAddress
      columnPrefix: false
    details:
      class: Gyman\Domain\Model\Details
      columnPrefix: false

  id:
    id:
      type: guid
      generator: { strategy: UUID }

  gedmo:
    soft_deleteable:
      field_name: deletedAt
      time_aware: false

  manyToMany:
    sections:
      targetEntity: Gyman\Bundle\AppBundle\Entity\Section
      inversedBy: members

  oneToMany:
    vouchers:
      targetEntity: Gyman\Bundle\AppBundle\Entity\Voucher
      mappedBy: member
      cascade: ["all"]

    entries:
      targetEntity: Gyman\Bundle\AppBundle\Entity\Entry
      mappedBy: member
      cascade: ["all"]

  oneToOne:
    currentVoucher:
      targetEntity: Gyman\Bundle\AppBundle\Entity\Voucher
      cascade: ["all"]
      inversedBy: member
      joinColumn:
        name: current_voucher_id
        referencedColumnName: id
        onDelete: SET NULL
        nullable: true

    lastEntry:
      targetEntity: Gyman\Bundle\AppBundle\Entity\Entry
      cascade: ["all"]
      joinColumn:
        name: last_entry_id
        referencedColumnName: id
        onDelete: SET NULL
        nullable: true

  fields:
    nameSlug:
      name: name_slug
      type: string
      nullable: true
      gedmo:
        slug:
          fields: [ details.firstname, details.lastname]
          updatable: true
          separator: -
          unique: true

    deletedAt:
      name: deleted_at
      type: datetime
      nullable: true #false

    createdAt:
      name: created_at
      type: datetime
      nullable: true
      gedmo:
        timestampable:
          on: create

    updatedAt:
      name: updated_at
      type: datetime
      nullable: true
      gedmo:
        timestampable:
          on: update
