Gyman\Domain\Section:
  type:   entity
  table:  sections
  repositoryClass: Gyman\Bundle\AppBundle\Repository\SectionRepository

  id:
    id:
      type: guid
      generator: { strategy: UUID }

  oneToOne:
    calendar:
      targetEntity: Gyman\Domain\Calendar
      cascade: ["all"]
      joinColumn:
        onDelete: CASCADE

  manyToMany:
    members:
      targetEntity: Gyman\Domain\Member
#      inversedBy: sections
      mappedBy: sections
  fields:
    title:
      type: string
      nullable: false
      unique: true
      length: 60