Gyman\Domain\Section:
  type:   entity
  table:  sections
  repositoryClass: Gyman\Bundle\AppBundle\Repository\SectionRepository

  id:
    id:
      type: integer
      generator: { strategy: auto }

  embedded:
    sectionId:
      class: Gyman\Domain\Section\SectionId
      columnPrefix: section_

  oneToOne:
    calendar:
      targetEntity: Gyman\Domain\Calendar
      inversedBy: section
      cascade: ["all"]
      joinColumn:
        onDelete: CASCADE

  manyToMany:
    members:
      targetEntity: Gyman\Domain\Member
#      inversedBy: sections
      mappedBy: sections
  fields:
    title:
      type: string
      nullable: false
      unique: false
      length: 60

    deletedAt:
      type: datetime
      nullable: true
      column: deleted_at

    createdAt:
      name: created_at
      type: datetime
      nullable: true
      gedmo:
        timestampable:
          on: create

    updatedAt:
      name: updated_at
      type: datetime
      nullable: true
      gedmo:
        timestampable:
          on: update

  gedmo:
    soft_deleteable:
      field_name: deletedAt
      time_aware: false