Gyman\Bundle\AppBundle\Entity\Section:
  type:   entity
  table:  sections
  repositoryClass: Gyman\Bundle\AppBundle\Entity\SectionRepository

  id:
    id:
      type: guid
      generator: { strategy: UUID }

  oneToOne:
    calendar:
      targetEntity: Dende\Calendar\Domain\Calendar
      cascade: ["all"]
      joinColumn:
        onDelete: CASCADE

  manyToMany:
    members:
      targetEntity: Gyman\Bundle\AppBundle\Entity\Member
      mappedBy: sections

  fields:
    title:
      type: text
      nullable: false
