Gyman\Bundle\AppBundle\Entity\Section:
  type:   entity
  table:  sections

  id:
    id:
      type: guid
      generator: { strategy: UUID }

  oneToOne:
    calendar:
      targetEntity: Dende\Calendar\Domain\Calendar

  manyToMany:
    members:
      targetEntity: Gyman\Bundle\AppBundle\Entity\Member

  fields:
    title:
      type: text
      nullable: false
