Gyman\Domain\User:
  type:   entity
  table:  users
  repositoryClass:  Gyman\Bundle\AppBundle\Repository\UserRepository

  id:
    id:
      type: integer
      generator: { strategy: auto }

  oneToOne:
    member:
      targetEntity: Gyman\Domain\Member

  fields:
    firstname:
      type: string
      length: 255
      nullable: true

    lastname:
      type: string
      length: 255
      nullable: true

    invitationToken:
      type: string
      length: 255
      nullable: true