Gyman\Bundle\AppBundle\Entity\Voucher:
  type:   entity
  table:  vouchers
  repositoryClass:  Gyman\Bundle\AppBundle\Entity\VoucherRepository
  embedded:
    price:
      class: Gyman\Domain\Model\Price
      columnPrefix: false

  id:
    id:
      type: integer
      generator: { strategy: AUTO }

  gedmo:
    soft_deleteable:
      field_name: deletedAt
      time_aware: false

  manyToOne:
    member:
      targetEntity: Gyman\Bundle\AppBundle\Entity\Member
      inversedBy: vouchers
      cascade: ["all"]

  oneToMany:
    entries:
      targetEntity: Gyman\Bundle\AppBundle\Entity\Entry
      mappedBy: voucher

  fields:
    startDate:
      type: datetime
      nullable: true #false

    endDate:
      type: datetime
      nullable: true #false

    maximumAmount:
      type: integer
      nullable: true

    deletedAt:
      name: deleted_at
      type: datetime
      nullable: true #false

    createdAt:
      name: created_at
      type: datetime
      nullable: true
      gedmo:
        timestampable:
          on: create

    updatedAt:
      name: updated_at
      type: datetime
      nullable: true
      gedmo:
        timestampable:
          on: update
