<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'gyman.dashboard.menu.main' shared service.

return $this->services['gyman.dashboard.menu.main'] = ${($_ = isset($this->services['gyman.dashboard.menu_builder']) ? $this->services['gyman.dashboard.menu_builder'] : $this->load(__DIR__.'/getGyman_Dashboard_MenuBuilderService.php')) && false ?: '_'}->actions();
