<?php
namespace Gyman\Bundle\ScheduleBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EventMetaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OccurrenceRepository extends EntityRepository
{
    public function getOccurrencesForPeriod(\DateTime $startDate, \DateTime $endDate)
    {
        $query = $this->getOccurrencesForPeriodQueryBuilder($startDate, $endDate);

        return $query->getQuery()->execute();
    }

    public function deleteFollowing(Serial $occurrence)
    {
        $query = $this->getDeleteFollowingQueryBuilder($occurrence);

        return $query->getQuery()->execute();
    }

    public function getDeleteFollowingQueryBuilder(Serial $occurrence)
    {
        return $this->createQueryBuilder('o')
                        ->delete()
                        ->where('o.startDate >= :date')
                        ->andWhere('o.event = :event')
                        ->setParameter('date', $occurrence->getStartDate())
                        ->setParameter('event', $occurrence->getEvent());
    }

    public function getOccurrencesForPeriodQueryBuilder(\DateTime $startDate, \DateTime $endDate)
    {
        return $queryBuilder = $this->createQueryBuilder('o')
                ->where('o.startDate BETWEEN :start AND :end')
                ->orderBy('o.startDate', 'ASC')
                ->setParameters([
            'start' => $startDate,
            'end'   => $endDate,
        ]);
    }
}
