parameters:
    base_manager.class: Dende\EntriesBundle\Services\Manager\BaseManager
    entry_entity.class: Dende\EntriesBundle\Entity\Entry
    entry_manager.class: Dende\EntriesBundle\Services\Manager\EntryManager
    entry_repository.class: Dende\EntriesBundle\Entity\EntryRepository

services:
    base_manager:
        class:     "%base_manager.class%"
        calls:
             - [ setContainer, ["@service_container"] ]
    entry_repository:
        class:          "%entry_repository.class%"
        factory_service: doctrine
        factory_method:  getRepository
        arguments: [ "%entry_entity.class%" ]
        
    entry_manager:
        class:          "%entry_manager.class%"
        parent:         base_manager
        calls:
             - [ setClass, [%entry_entity.class%] ]
             - [ setRepository, ["@entry_repository"] ]
