parameters:
    base_manager.class: Dende\MembersBundle\Services\Manager\BaseManager
    member_entity.class: Dende\MembersBundle\Entity\Member
    member_manager.class: Dende\MembersBundle\Services\Manager\MemberManager

services:
    base_manager:
        class:     "%base_manager.class%"
        calls:
             - [ setContainer, ["@service_container"] ]
    member_manager:
        class:          "%member_manager.class%"
        parent:         base_manager
        calls:
             - [ setClass, [%member_entity.class%] ]

    dende.twig.age_extension:
        class: Dende\MembersBundle\Twig\AgeExtension
        tags:
            - { name: twig.extension }

    dende.upload_listener:
        class: Dende\MembersBundle\Services\Listener\UploadListener
        arguments: [@doctrine]
        tags:
            - { name: kernel.event_listener, event : oneup_uploader.post_persist, method: onUpload}