parameters:
    member_entity.class: Dende\MembersBundle\Entity\Member
    member_manager.class: Dende\MembersBundle\Services\Manager\MemberManager
    member_repository.class: Dende\MembersBundle\Entity\MemberRepository

services:
    member_repository:
        class:     "%member_repository.class%"
        factory_service: doctrine
        factory_method: getRepository
        arguments: [ %member_entity.class% ]
    member_manager:
        class:     "%member_manager.class%"
        calls:
            - [setRepository, ["@member_repository"]]
    dende.twig.age_extension:
        class: Dende\MembersBundle\Twig\AgeExtension
        tags:
            - { name: twig.extension }
