services:
  gyman.club.club_manager:
    class: Gyman\Bundle\ClubBundle\EntityManager\ClubManager
    parent: gyman.base.entity_manager

  gyman.club.repository:
      class:  "Gyman\Bundle\ClubBundle\Entity\ClubRepository"
      factory_method: getRepository
      factory_service: doctrine.orm.default_entity_manager
      arguments: ["Gyman\Bundle\ClubBundle\Entity\Club"]

  gyman.club.provider:
    class: Gyman\Bundle\ClubBundle\Services\ClubProvider
    arguments:
      - @=service(parameter('subdomain_provider_service'))
      - @gyman.club.repository