<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'dende_calendar.id_generator' shared service.

return $this->services['dende_calendar.id_generator'] = new \Dende\Calendar\Application\Generator\Doctrine\IdGenerator(${($_ = isset($this->services['dende_calendar.entity_manager']) ? $this->services['dende_calendar.entity_manager'] : $this->load(__DIR__.'/getDendeCalendar_EntityManagerService.php')) && false ?: '_'});
