<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'fos_user.command.promote_user' shared service.

$this->services['fos_user.command.promote_user'] = $instance = new \FOS\UserBundle\Command\PromoteUserCommand();

$instance->setName('fos:user:promote');

return $instance;
