<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'gyman.reports.generator' shared service.

$this->services['gyman.reports.generator'] = $instance = new \Gyman\Bundle\ReportsBundle\Generator\ReportsGenerator(${($_ = isset($this->services['router']) ? $this->services['router'] : $this->getRouterService()) && false ?: '_'});

$instance->addStrategy('all', ${($_ = isset($this->services['gyman.reports.strategy.all']) ? $this->services['gyman.reports.strategy.all'] : $this->load(__DIR__.'/getGyman_Reports_Strategy_AllService.php')) && false ?: '_'});
$instance->addStrategy('per-member', ${($_ = isset($this->services['gyman.reports.strategy.per_member']) ? $this->services['gyman.reports.strategy.per_member'] : $this->load(__DIR__.'/getGyman_Reports_Strategy_PerMemberService.php')) && false ?: '_'});
$instance->addStrategy('per-section', ${($_ = isset($this->services['gyman.reports.strategy.per_section']) ? $this->services['gyman.reports.strategy.per_section'] : $this->load(__DIR__.'/getGyman_Reports_Strategy_PerSectionService.php')) && false ?: '_'});

return $instance;
