<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'monolog.logger.createNewClub' shared service.

$this->services['monolog.logger.createNewClub'] = $instance = new \Symfony\Bridge\Monolog\Logger('createNewClub');

$instance->pushProcessor(${($_ = isset($this->services['debug.log_processor']) ? $this->services['debug.log_processor'] : $this->services['debug.log_processor'] = new \Symfony\Bridge\Monolog\Processor\DebugProcessor()) && false ?: '_'});
$instance->pushHandler(${($_ = isset($this->services['monolog.handler.grouped_main']) ? $this->services['monolog.handler.grouped_main'] : $this->getMonolog_Handler_GroupedMainService()) && false ?: '_'});
$instance->pushHandler(${($_ = isset($this->services['monolog.handler.createNewClub']) ? $this->services['monolog.handler.createNewClub'] : $this->load(__DIR__.'/getMonolog_Handler_CreateNewClubService.php')) && false ?: '_'});
$instance->pushHandler(${($_ = isset($this->services['monolog.handler.main']) ? $this->services['monolog.handler.main'] : $this->getMonolog_Handler_MainService()) && false ?: '_'});

return $instance;
