<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'gyman.app.handler.settings_update' shared service.

return $this->services['gyman.app.handler.settings_update'] = new \Gyman\Bundle\AppBundle\Services\SettingsUpdateHandler(${($_ = isset($this->services['gyman.repository.section']) ? $this->services['gyman.repository.section'] : $this->load(__DIR__.'/getGyman_Repository_SectionService.php')) && false ?: '_'}, ${($_ = isset($this->services['gyman.club.repository']) ? $this->services['gyman.club.repository'] : $this->getGyman_Club_RepositoryService()) && false ?: '_'}, ${($_ = isset($this->services['gyman.club.provider']) ? $this->services['gyman.club.provider'] : $this->load(__DIR__.'/getGyman_Club_ProviderService.php')) && false ?: '_'}->club(), ${($_ = isset($this->services['gyman.members.upload_club_logo_handler']) ? $this->services['gyman.members.upload_club_logo_handler'] : $this->load(__DIR__.'/getGyman_Members_UploadClubLogoHandlerService.php')) && false ?: '_'});
