Gyman\Bundle\ClubBundle\Entity\Club:
  type:   entity
  table:  clubs
  repositoryClass:  Gyman\Bundle\ClubBundle\Entity\ClubRepository
  embedded:
    details:
      class: Gyman\Bundle\ClubBundle\Entity\Details
      columnPrefix: details_
    database:
      class: Gyman\Bundle\ClubBundle\Entity\Database
      columnPrefix: database_
    subdomain:
      class: Gyman\Bundle\ClubBundle\Entity\Subdomain
      columnPrefix: subdomain_

  id:
    id:
      type: integer
      generator: { strategy: AUTO }


  fields:
    name:
      type: string
      length: 255
    enabled:
      type: boolean
      nullable: false
      options:
        default: true
    deletedAt:
      type: datetime
      nullable: true