<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'app.listener.open_entry' shared service.

return $this->services['app.listener.open_entry'] = new \Gyman\Bundle\AppBundle\Listener\OpenCreditEntryListener(${($_ = isset($this->services['mailer.credit_entry']) ? $this->services['mailer.credit_entry'] : $this->load(__DIR__.'/getMailer_CreditEntryService.php')) && false ?: '_'});
