<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'dende_calendar.manager.update_occurrence' shared service.

$this->services['dende_calendar.manager.update_occurrence'] = $instance = new \Dende\Calendar\Application\Service\OccurrenceUpdateManager($this->get($this->getParameter("dende_calendar.event_repository_service_name")), $this->get($this->getParameter("dende_calendar.occurrence_repository_service_name")));

$instance->addStrategy('single', ${($_ = isset($this->services['dende_calendar.update_strategy.single']) ? $this->services['dende_calendar.update_strategy.single'] : $this->services['dende_calendar.update_strategy.single'] = new \Dende\Calendar\Application\Service\UpdateStrategy\Single()) && false ?: '_'});

return $instance;
