<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'gyman.club.unique_subdomain.validator' shared service.

return $this->services['gyman.club.unique_subdomain.validator'] = new \Gyman\Bundle\AppBundle\Validator\UniqueClubSubdomainValidator(${($_ = isset($this->services['gyman.club.repository']) ? $this->services['gyman.club.repository'] : $this->getGyman_Club_RepositoryService()) && false ?: '_'});
