<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'app.listener.user_for_member_created' shared service.

return $this->services['app.listener.user_for_member_created'] = new \Gyman\Bundle\AppBundle\Listener\UserCreatedForMemberListener(${($_ = isset($this->services['mailer.member_invitation']) ? $this->services['mailer.member_invitation'] : $this->load(__DIR__.'/getMailer_MemberInvitationService.php')) && false ?: '_'});
