<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'dende_multitenancy.listener.command' shared service.

return $this->services['dende_multitenancy.listener.command'] = new \Dende\MultitenancyBundle\Listener\CommandListener(${($_ = isset($this->services['dende_multitenancy.tenant_manager']) ? $this->services['dende_multitenancy.tenant_manager'] : $this->getDendeMultitenancy_TenantManagerService()) && false ?: '_'}, ${($_ = isset($this->services['doctrine.dbal.default_connection']) ? $this->services['doctrine.dbal.default_connection'] : $this->getDoctrine_Dbal_DefaultConnectionService()) && false ?: '_'}->getSchemaManager(), $this->parameters['dende_multitenancy.config.patched_commands'], $this->parameters['dende_multitenancy.config.command_listener_config']);
