<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'dende_calendar.handler.update_occurrence' shared service.

return $this->services['dende_calendar.handler.update_occurrence'] = new \Dende\Calendar\Application\Handler\UpdateOccurrenceHandler(${($_ = isset($this->services['dende_calendar.manager.update_occurrence']) ? $this->services['dende_calendar.manager.update_occurrence'] : $this->load(__DIR__.'/getDendeCalendar_Manager_UpdateOccurrenceService.php')) && false ?: '_'});
