<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'gyman.app.twig.entries_extension' shared service.

return $this->services['gyman.app.twig.entries_extension'] = new \Gyman\Bundle\AppBundle\Twig\EntriesExtension();
