<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'gyman.club.provider' shared service.

return $this->services['gyman.club.provider'] = new \Gyman\Bundle\ClubBundle\Services\ClubProvider($this->get($this->getParameter("subdomain_provider_service")), ${($_ = isset($this->services['gyman.club.repository']) ? $this->services['gyman.club.repository'] : $this->getGyman_Club_RepositoryService()) && false ?: '_'});
