<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'gyman.app.command.clear_entries' shared service.

$this->services['gyman.app.command.clear_entries'] = $instance = new \Gyman\Bundle\AppBundle\Command\CloseEntriesCommand();

$instance->setLogger(${($_ = isset($this->services['monolog.logger.commands']) ? $this->services['monolog.logger.commands'] : $this->load(__DIR__.'/getMonolog_Logger_CommandsService.php')) && false ?: '_'});

return $instance;
