<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'gyman.entries.price_set_for_paid_entry.validator' shared service.

return $this->services['gyman.entries.price_set_for_paid_entry.validator'] = new \Gyman\Bundle\AppBundle\Validator\PriceSetForPaidEntryValidator();
