<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'gyman.vouchers.create_voucher' shared service.

return $this->services['gyman.vouchers.create_voucher'] = new \Gyman\Application\Handler\CreateVoucherHandler(${($_ = isset($this->services['gyman.members.repository']) ? $this->services['gyman.members.repository'] : $this->load(__DIR__.'/getGyman_Members_RepositoryService.php')) && false ?: '_'}, ${($_ = isset($this->services['gyman.entries.repository']) ? $this->services['gyman.entries.repository'] : $this->load(__DIR__.'/getGyman_Entries_RepositoryService.php')) && false ?: '_'}, ${($_ = isset($this->services['event_dispatcher']) ? $this->services['event_dispatcher'] : $this->getEventDispatcherService()) && false ?: '_'});
