<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'gyman.app.twig.avatar' shared service.

return $this->services['gyman.app.twig.avatar'] = new \Gyman\Twig\Extension\Avatar(${($_ = isset($this->services['gyman.club.provider']) ? $this->services['gyman.club.provider'] : $this->load(__DIR__.'/getGyman_Club_ProviderService.php')) && false ?: '_'}->club(), '/vagrant/app/../web/uploads/gallery/', '/uploads/gallery/');
