<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'gyman.members.update_member' shared service.

return $this->services['gyman.members.update_member'] = new \Gyman\Application\Handler\UpdateMemberHandler(${($_ = isset($this->services['gyman.members.repository']) ? $this->services['gyman.members.repository'] : $this->load(__DIR__.'/getGyman_Members_RepositoryService.php')) && false ?: '_'}, ${($_ = isset($this->services['gyman.members.upload_member_foto_handler']) ? $this->services['gyman.members.upload_member_foto_handler'] : $this->load(__DIR__.'/getGyman_Members_UploadMemberFotoHandlerService.php')) && false ?: '_'}, ${($_ = isset($this->services['event_dispatcher']) ? $this->services['event_dispatcher'] : $this->getEventDispatcherService()) && false ?: '_'});
