<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'gyman.app.test_subdomain_provider' shared service.

return $this->services['gyman.app.test_subdomain_provider'] = new \Gyman\Bundle\AppBundle\Services\TestSubdomainProvider();
