<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'security.access_map' shared service.

$this->services['security.access_map'] = $instance = new \Symfony\Component\Security\Http\AccessMap();

$instance->add(new \Symfony\Component\HttpFoundation\RequestMatcher('^/login$'), array(0 => 'IS_AUTHENTICATED_ANONYMOUSLY'), NULL);
$instance->add(new \Symfony\Component\HttpFoundation\RequestMatcher('^/calendar/events'), array(0 => 'IS_AUTHENTICATED_ANONYMOUSLY'), NULL);
$instance->add(new \Symfony\Component\HttpFoundation\RequestMatcher('^/calendar/'), array(0 => 'ROLE_MODERATOR'), NULL);
$instance->add(new \Symfony\Component\HttpFoundation\RequestMatcher('^/members'), array(0 => 'ROLE_MODERATOR'), NULL);
$instance->add(new \Symfony\Component\HttpFoundation\RequestMatcher('^/vouchers'), array(0 => 'ROLE_MODERATOR'), NULL);
$instance->add(new \Symfony\Component\HttpFoundation\RequestMatcher('^/entries'), array(0 => 'ROLE_MODERATOR'), NULL);
$instance->add(new \Symfony\Component\HttpFoundation\RequestMatcher('^/reports'), array(0 => 'ROLE_MODERATOR'), NULL);
$instance->add(new \Symfony\Component\HttpFoundation\RequestMatcher('^/register'), array(0 => 'ROLE_SUPER_ADMIN'), NULL);
$instance->add(new \Symfony\Component\HttpFoundation\RequestMatcher('^/resetting'), array(0 => 'ROLE_SUPER_ADMIN'), NULL);
$instance->add(new \Symfony\Component\HttpFoundation\RequestMatcher('^/dashboard/member'), array(0 => 'ROLE_MEMBER'), NULL);
$instance->add(new \Symfony\Component\HttpFoundation\RequestMatcher('^/dashboard'), array(0 => 'ROLE_MODERATOR', 1 => 'ROLE_MEMBER'), NULL);
$instance->add(new \Symfony\Component\HttpFoundation\RequestMatcher('^/profile'), array(0 => 'IS_AUTHENTICATED_REMEMBERED'), NULL);
$instance->add(new \Symfony\Component\HttpFoundation\RequestMatcher('^/admin'), array(0 => 'ROLE_SUPER_ADMIN'), NULL);
$instance->add(new \Symfony\Component\HttpFoundation\RequestMatcher('^/settings'), array(0 => 'ROLE_ADMIN'), NULL);
$instance->add(new \Symfony\Component\HttpFoundation\RequestMatcher('^/'), array(0 => 'IS_AUTHENTICATED_ANONYMOUSLY'), NULL);

return $instance;
