<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'twig.loader' shared service.

$this->services['twig.loader'] = $instance = new \Symfony\Bundle\TwigBundle\Loader\FilesystemLoader(${($_ = isset($this->services['templating.locator']) ? $this->services['templating.locator'] : $this->load(__DIR__.'/getTemplating_LocatorService.php')) && false ?: '_'}, ${($_ = isset($this->services['templating.name_parser']) ? $this->services['templating.name_parser'] : $this->services['templating.name_parser'] = new \Symfony\Bundle\FrameworkBundle\Templating\TemplateNameParser(${($_ = isset($this->services['kernel']) ? $this->services['kernel'] : $this->get('kernel')) && false ?: '_'})) && false ?: '_'}, '/vagrant');

$instance->addPath('/vagrant/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Resources/views', 'Framework');
$instance->addPath('/vagrant/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Resources/views', '!Framework');
$instance->addPath('/vagrant/vendor/symfony/symfony/src/Symfony/Bundle/SecurityBundle/Resources/views', 'Security');
$instance->addPath('/vagrant/vendor/symfony/symfony/src/Symfony/Bundle/SecurityBundle/Resources/views', '!Security');
$instance->addPath('/vagrant/app/Resources/TwigBundle/views', 'Twig');
$instance->addPath('/vagrant/vendor/symfony/symfony/src/Symfony/Bundle/TwigBundle/Resources/views', 'Twig');
$instance->addPath('/vagrant/vendor/symfony/symfony/src/Symfony/Bundle/TwigBundle/Resources/views', '!Twig');
$instance->addPath('/vagrant/vendor/symfony/swiftmailer-bundle/Resources/views', 'Swiftmailer');
$instance->addPath('/vagrant/vendor/symfony/swiftmailer-bundle/Resources/views', '!Swiftmailer');
$instance->addPath('/vagrant/vendor/knplabs/knp-menu-bundle/src/Resources/views', 'KnpMenu');
$instance->addPath('/vagrant/vendor/knplabs/knp-menu-bundle/src/Resources/views', '!KnpMenu');
$instance->addPath('/vagrant/app/Resources/FOSUserBundle/views', 'FOSUser');
$instance->addPath('/vagrant/vendor/friendsofsymfony/user-bundle/Resources/views', 'FOSUser');
$instance->addPath('/vagrant/vendor/friendsofsymfony/user-bundle/Resources/views', '!FOSUser');
$instance->addPath('/vagrant/vendor/doctrine/doctrine-bundle/Resources/views', 'Doctrine');
$instance->addPath('/vagrant/vendor/doctrine/doctrine-bundle/Resources/views', '!Doctrine');
$instance->addPath('/vagrant/vendor/liip/monitor-bundle/Resources/views', 'LiipMonitor');
$instance->addPath('/vagrant/vendor/liip/monitor-bundle/Resources/views', '!LiipMonitor');
$instance->addPath('/vagrant/app/Resources/DendeCalendarBundle/views', 'DendeCalendar');
$instance->addPath('/vagrant/vendor/dende/calendar-bundle/Resources/views', 'DendeCalendar');
$instance->addPath('/vagrant/vendor/dende/calendar-bundle/Resources/views', '!DendeCalendar');
$instance->addPath('/vagrant/src/Bundle/DashboardBundle/Resources/views', 'Dashboard');
$instance->addPath('/vagrant/src/Bundle/DashboardBundle/Resources/views', '!Dashboard');
$instance->addPath('/vagrant/src/Bundle/ChartsBundle/Resources/views', 'Charts');
$instance->addPath('/vagrant/src/Bundle/ChartsBundle/Resources/views', '!Charts');
$instance->addPath('/vagrant/src/Bundle/ClubBundle/Resources/views', 'Club');
$instance->addPath('/vagrant/src/Bundle/ClubBundle/Resources/views', '!Club');
$instance->addPath('/vagrant/src/Bundle/AccountBundle/Resources/views', 'Account');
$instance->addPath('/vagrant/src/Bundle/AccountBundle/Resources/views', '!Account');
$instance->addPath('/vagrant/src/Bundle/MailerBundle/Resources/views', 'Mailer');
$instance->addPath('/vagrant/src/Bundle/MailerBundle/Resources/views', '!Mailer');
$instance->addPath('/vagrant/src/Bundle/BaseBundle/Resources/views', 'Base');
$instance->addPath('/vagrant/src/Bundle/BaseBundle/Resources/views', '!Base');
$instance->addPath('/vagrant/src/Bundle/AppBundle/Resources/views', 'GymanApp');
$instance->addPath('/vagrant/src/Bundle/AppBundle/Resources/views', '!GymanApp');
$instance->addPath('/vagrant/src/Bundle/ReportsBundle/Resources/views', 'GymanReports');
$instance->addPath('/vagrant/src/Bundle/ReportsBundle/Resources/views', '!GymanReports');
$instance->addPath('/vagrant/src/Bundle/LandingPageBundle/Resources/views', 'GymanLandingPage');
$instance->addPath('/vagrant/src/Bundle/LandingPageBundle/Resources/views', '!GymanLandingPage');
$instance->addPath('/vagrant/src/Bundle/SettingsBundle/Resources/views', 'GymanSettings');
$instance->addPath('/vagrant/src/Bundle/SettingsBundle/Resources/views', '!GymanSettings');
$instance->addPath('/vagrant/app/Resources/views');
$instance->addPath('/vagrant/vendor/symfony/symfony/src/Symfony/Bridge/Twig/Resources/views/Form');
$instance->addPath('/vagrant/vendor/knplabs/knp-menu/src/Knp/Menu/Resources/views');

return $instance;
