<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'time.datetime_formatter' shared service.

return $this->services['time.datetime_formatter'] = new \Knp\Bundle\TimeBundle\DateTimeFormatter(${($_ = isset($this->services['translator.default']) ? $this->services['translator.default'] : $this->getTranslator_DefaultService()) && false ?: '_'});
