<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'time.templating.helper.time' shared service.

return $this->services['time.templating.helper.time'] = new \Knp\Bundle\TimeBundle\Templating\Helper\TimeHelper(${($_ = isset($this->services['time.datetime_formatter']) ? $this->services['time.datetime_formatter'] : $this->load(__DIR__.'/getTime_DatetimeFormatterService.php')) && false ?: '_'});
