<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'gyman.landing.menu.tabs' shared service.

return $this->services['gyman.landing.menu.tabs'] = ${($_ = isset($this->services['gyman.landing.menu_builder']) ? $this->services['gyman.landing.menu_builder'] : $this->load(__DIR__.'/getGyman_Landing_MenuBuilderService.php')) && false ?: '_'}->tabs();
