<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'gyman.app.subdomain_provider' shared service.

return $this->services['gyman.app.subdomain_provider'] = new \Gyman\Bundle\AppBundle\Services\SubdomainProvider(${($_ = isset($this->services['request_stack']) ? $this->services['request_stack'] : $this->services['request_stack'] = new \Symfony\Component\HttpFoundation\RequestStack()) && false ?: '_'}, 'gyman.vagrant');
