<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'gyman.landing.menu_builder' shared service.

return $this->services['gyman.landing.menu_builder'] = new \Gyman\Bundle\AppBundle\Menu\LandingBuilder(${($_ = isset($this->services['knp_menu.factory']) ? $this->services['knp_menu.factory'] : $this->load(__DIR__.'/getKnpMenu_FactoryService.php')) && false ?: '_'});
