<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'gyman.vouchers.close_voucher' shared service.

return $this->services['gyman.vouchers.close_voucher'] = new \Gyman\Application\Service\CloseVoucher(${($_ = isset($this->services['gyman.vouchers.repository']) ? $this->services['gyman.vouchers.repository'] : $this->load(__DIR__.'/getGyman_Vouchers_RepositoryService.php')) && false ?: '_'}, ${($_ = isset($this->services['gyman.members.repository']) ? $this->services['gyman.members.repository'] : $this->load(__DIR__.'/getGyman_Members_RepositoryService.php')) && false ?: '_'}, ${($_ = isset($this->services['debug.event_dispatcher']) ? $this->services['debug.event_dispatcher'] : $this->getDebug_EventDispatcherService()) && false ?: '_'});
