<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'memcached' shared service.

$this->services['memcached'] = $instance = new \Memcached();

$instance->addServers($this->parameters['memcached.servers']);

return $instance;
