services:
    gyman.default.command:
      abstract: true
      class: Gyman\Bundle\DefaultBundle\Command\AbstractCommand
      calls:
        - [setDatabaseWorker, [@gyman.default.database_worker]]

    gyman.default.command.create_database:
      class: Gyman\Bundle\DefaultBundle\Command\CreateClubDatabaseCommand
      parent: gyman.default.command
      tags:
        - { name: console.command }

    gyman.default.command.drop_database:
      class: Gyman\Bundle\DefaultBundle\Command\DropClubDatabaseCommand
      parent: gyman.default.command
      tags:
        - { name: console.command }

    gyman.default.command.load_fixtures:
      class: Gyman\Bundle\DefaultBundle\Command\LoadClubFixturesCommand
      parent: gyman.default.command
      tags:
        - { name: console.command }