parameters:
    memcached.servers:
      - { host: 127.0.0.1, port: 11211 }

services:
    gedmo.listener.softdeleteable:
        class: Gedmo\SoftDeleteable\SoftDeleteableListener
        tags:
            - { name: doctrine.event_subscriber, connection: default }
        calls:
            - [ setAnnotationReader, [ @annotation_reader ] ]

    memcached:
        class: Memcached
        calls:
            - [ addServers, [ %memcached.servers% ]]

    gyman.default.request.arraycollection_converter:
      class: Gyman\Bundle\DefaultBundle\Request\ArrayCollectionConverter
      calls:
        - [setEntityManager, [@doctrine.orm.default_entity_manager]]
      tags:
        - { name: request.param_converter}

    gyman.default.menu_builder:
        class: Gyman\Bundle\DefaultBundle\Menu\Builder
        arguments: [@knp_menu.factory, @security.context]

    gyman.default.menu.main:
        class:            Knp\Menu\MenuItem
        factory_service:  gyman.default.menu_builder
        factory_method:   main
        arguments:        ["@request"]
        scope:            request
        tags:
            - { name: knp_menu.menu, alias: main }

    gyman.default.menu.profile:
        class: Knp\Menu\MenuItem
        factory_service: gyman.default.menu_builder
        factory_method: profile
        arguments: ["@request"]
        scope: request
        tags:
            - { name: knp_menu.menu, alias: profile }

#    gyman.default.menu_abstract:
#        abstract: true
#        class: Knp\Menu\MenuItem
#        factory_service: gyman.default.menu_builder
#        arguments: ["@request"]
#        scope: request
#
#    gyman.default.menu.profile:
#        parent: gyman.default.menu_abstract
#        tags:
#            - { name: knp_menu.menu, alias: main }
#
#    gyman.default.menu.profile:
#        parent: gyman.default.menu_abstract
#        tags:
#            - { name: knp_menu.menu, alias: main }
