imports:
  - { resource: menu.yml }

services:
    gyman.default.request.arraycollection_converter:
      class: Gyman\Bundle\DefaultBundle\Request\ArrayCollectionConverter
      calls:
        - [setEntityManager, [@doctrine.orm.club_entity_manager]]
      tags:
        - { name: request.param_converter}

#    gyman.default.menu_abstract:
#        abstract: true
#        class: Knp\Menu\MenuItem
#        factory_service: gyman.default.menu_builder
#        arguments: ["@request"]
#        scope: request
#
#    gyman.default.menu.profile:
#        parent: gyman.default.menu_abstract
#        tags:
#            - { name: knp_menu.menu, alias: main }
#
#    gyman.default.menu.profile:
#        parent: gyman.default.menu_abstract
#        tags:
#            - { name: knp_menu.menu, alias: main }
