#@todo: refactoring

parameters:
    activity_entity.class: Gyman\Bundle\ScheduleBundle\Entity\Activity
    activity_repository.class: Gyman\Bundle\ScheduleBundle\Entity\ActivityRepository
    event_entity.class: Gyman\Bundle\ScheduleBundle\Entity\Event
    event_repository.class: Gyman\Bundle\ScheduleBundle\Entity\EventRepository
    occurrence_entity.class: Gyman\Bundle\ScheduleBundle\Entity\Occurrence
    occurrence_repository.class: Gyman\Bundle\ScheduleBundle\Entity\OccurrenceRepository

services:
    activity_manager:
        class:          Gyman\Bundle\ScheduleBundle\Services\Manager\ActivityManager
        parent:         gyman.base.entity_manager
        calls:
          - [ setEntityManager, [@doctrine.orm.club_entity_manager]]

    event_manager:
        class:          Gyman\Bundle\ScheduleBundle\Services\Manager\EventManager
        parent:         gyman.base.entity_manager
        calls:
          - [ setEntityManager, [@doctrine.orm.club_entity_manager]]

    event_repository:
        class:              %event_repository.class%
        factory_service:    doctrine.orm.club_entity_manager
        factory_method:     getRepository
        arguments:          [ %event_entity.class% ]

    occurrence_repository:
        class:              %occurrence_repository.class%
        factory_service:    doctrine.orm.club_entity_manager
        factory_method:     getRepository
        arguments:          [ %occurrence_entity.class% ]

    activity_repository:
        class:              %activity_repository.class%
        factory_service:    doctrine.orm.club_entity_manager
        factory_method:     getRepository
        arguments:          [ %activity_entity.class% ]

    occurrences_manager:
        class: Gyman\Bundle\ScheduleBundle\Services\Manager\OccurrencesManager
        parent: gyman.base.entity_manager
        calls:
           - [ setRouter, ["@router"] ]
           - [ setEntityManager, [@doctrine.orm.club_entity_manager]]

    schedule:
        class: Gyman\Bundle\ScheduleBundle\Services\Schedule
        calls:
             - [ setContainer, ["@service_container"] ]
