<?php
namespace Gyman\Bundle\ScheduleBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query\Expr\Join;

/**
 * ActivityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActivityRepository extends EntityRepository
{
    public function getActivitiesQuery()
    {
        return $this->createQueryBuilder('a')
                ->select();
    }

    public function getPopularityQueryBuilder()
    {
        return $this->createQueryBuilder('a')
                ->select('a.name', 'count(en.id) as cnt')
                ->join('a.events', 'e')
                ->join('e.occurences', 'o')
                ->join('o.entries', 'en')
                ->setMaxResults(6)
                ->groupBy('a.name')
                ->orderBy('cnt', 'DESC');
    }

    public function getCountByActivities()
    {
        $query = $this->getPopularityQueryBuilder();

        return $query->getQuery()->execute();
    }

    public function getAllActivities()
    {
        return $this->getActivitiesQuery()->getQuery()->execute();
    }
}
