<?php

namespace Gyman\Bundle\ScheduleBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EventMetaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OccurenceRepository extends EntityRepository
{
    public function getOccurencesForPeriod(\DateTime $startDate, \DateTime $endDate)
    {
        $query = $this->getOccurencesForPeriodQueryBuilder($startDate, $endDate);

        return $query->getQuery()->execute();
    }

    public function deleteFollowing(Serial $occurence)
    {
        $query = $this->getDeleteFollowingQueryBuilder($occurence);

        return $query->getQuery()->execute();
    }

    public function getDeleteFollowingQueryBuilder(Serial $occurence)
    {
        return $this->createQueryBuilder('o')
                        ->delete()
                        ->where('o.startDate >= :date')
                        ->andWhere('o.event = :event')
                        ->setParameter('date', $occurence->getStartDate())
                        ->setParameter('event', $occurence->getEvent());
    }

    public function getOccurencesForPeriodQueryBuilder(\DateTime $startDate, \DateTime $endDate)
    {
        return $queryBuilder = $this->createQueryBuilder('o')
                ->where('o.startDate BETWEEN :start AND :end')
                ->orderBy('o.startDate', 'ASC')
                ->setParameters([
            'start' => $startDate,
            'end'   => $endDate,
        ]);
    }
}
