services:
  admin_prelist_listener:
      class: Gyman\Bundle\AdminBundle\Listener\PreListListener
      arguments:
        - "@session"
        - "@dende_multitenancy.tenant_manager"
        - "@router"
        - "@gyman.club.repository"
      tags:
          - { name: kernel.event_listener, event: easy_admin.pre_initialize, method: onPreListEvent }

  gyman.form.member:
    class: Gyman\Bundle\AdminBundle\Form\MemberType
    arguments:
      - '@doctrine'
    tags:
      - { name: form.type, alias: members }
