Gyman\Bundle\ClubBundle\Entity\Involvement:
  type:   entity
  table:  involvement
  repositoryClass:  Gyman\Bundle\ClubBundle\Entity\ClubRepository

  id:
    id:
      type: guid
      generator: { strategy: UUID }

  manyToOne:
    user:
      targetEntity:   Gyman\Bundle\ClubBundle\Entity\User
#      mappedBy:       involvements
      inversedBy:       involvements

    club:
      targetEntity:   Gyman\Bundle\ClubBundle\Entity\Club
      mappedBy:       involvements

  fields:
    roles:
      type: json_array