Gyman\Bundle\ClubBundle\Entity\User:
  type:   entity
  table:  users
  repositoryClass:  Gyman\Bundle\ClubBundle\Entity\UserRepository

  id:
    id:
      type: guid
      generator: { strategy: UUID }

  oneToMany:
    involvements:
      targetEntity: Gyman\Bundle\ClubBundle\Entity\Involvement
      mappedBy: user
#      inversedBy: user

  fields:
    firstname:
      type: string
      length: 255
      nullable: true

    lastname:
      type: string
      length: 255
      nullable: true

