<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'fos_user.command.demote_user' shared service.

$this->services['fos_user.command.demote_user'] = $instance = new \FOS\UserBundle\Command\DemoteUserCommand();

$instance->setName('fos:user:demote');

return $instance;
