<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'gyman.entries.entry_form_type' shared service.

return $this->services['gyman.entries.entry_form_type'] = new \Gyman\Bundle\AppBundle\Form\EntryType(${($_ = isset($this->services['gyman.occurrence.repository']) ? $this->services['gyman.occurrence.repository'] : $this->load(__DIR__.'/getGyman_Occurrence_RepositoryService.php')) && false ?: '_'}, ${($_ = isset($this->services['gyman.repository.section']) ? $this->services['gyman.repository.section'] : $this->load(__DIR__.'/getGyman_Repository_SectionService.php')) && false ?: '_'});
