<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'liip_monitor.helper.raw_console_reporter' shared service.

return $this->services['liip_monitor.helper.raw_console_reporter'] = new \Liip\MonitorBundle\Helper\RawConsoleReporter();
