parameters:
    voucher_entity.class: Gyman\Bundle\VouchersBundle\Entity\Voucher
    voucher_repository.class: Gyman\Bundle\VouchersBundle\Entity\VoucherRepository
    voucher_manager.class: Gyman\Bundle\VouchersBundle\Services\Manager\VoucherManager
    date_validator.class: Gyman\Bundle\VouchersBundle\Validator\VoucherDateValidator
services:
    voucher_repository:
        class:          "%voucher_repository.class%"
        factory_service: doctrine
        factory_method:  getRepository
        arguments: [ "%voucher_entity.class%" ]

    voucher_manager:
        class:          "%voucher_manager.class%"
        parent:         base_manager
        calls:
             - [ setClass, [%voucher_entity.class%] ]
             - [ setRepository, ["@voucher_repository"] ]

    validator.voucher_date:
        class:          "%date_validator.class%"
        arguments:
            - "@voucher_manager"
        tags:
            - { name: validator.constraint_validator, alias: validator.voucher_date_constraint}

    dende.update_current_voucher_listener:
        class: Gyman\Bundle\VouchersBundle\Services\Listener\UpdateCurrentVoucherListener
        # TODO: very bad, temporarily workaround of circular
        arguments: ["@service_container"]
#         calls:
#             - [ setMemberManager, ["@member_manager"] ]
        tags:
            - { name: doctrine.event_listener, event: postPersist }
