Gyman\Bundle\VouchersBundle\Entity\Voucher:
  constraints:
    - Gyman\Bundle\VouchersBundle\Validator\VoucherDateConstraint:
  properties:
    startDate:
      - NotNull:
          message: Należy podać datę początkową.

Gyman\Component\VouchersBundle\Entity\Price:
  properties:
    amount:
      - Regex:
          pattern: "/^\d+(\.\d\d){0,1}$/"
    currency:
      - Range:
          min: 1
          max: 999
          minMessage: "Najmniejsza możliwa liczba wejść na karnet to 1"
          maxMessage: "Maksymalna liczba wejść na karnet to 999"

Gyman\Component\VouchersBundle\Entity\Entry:
  constraints:
    - Symfony\Component\Validator\Constraints\Callback:
      methods:
        - { "Gyman\Bundle\EntriesBundle\Validator\LeftAmountValidator", "isAmountLeft"}
        - { "Gyman\Bundle\EntriesBundle\Validator\PriceNotBlankIfPaidEntryTypeValidator", "isPaidAndPriceSet"}