<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container0cndtvb\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container0cndtvb/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container0cndtvb.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\Container0cndtvb\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \Container0cndtvb\appDevDebugProjectContainer();
