<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQgxwq97\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQgxwq97/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerQgxwq97.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerQgxwq97\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerQgxwq97\appDevDebugProjectContainer();
