<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'gyman.members.member_form_type' shared service.

return $this->services['gyman.members.member_form_type'] = new \Gyman\Bundle\AppBundle\Form\MemberType();
