<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'validator.voucher_date' shared service.

return $this->services['validator.voucher_date'] = new \Gyman\Bundle\AppBundle\Validator\VoucherDateValidator(${($_ = isset($this->services['voucher_manager']) ? $this->services['voucher_manager'] : $this->load(__DIR__.'/getVoucherManagerService.php')) && false ?: '_'});
